# Init

* Mount drive

* Install dependencies

* Navigate to necessary directory

* Read raw data

In [ ]:
%%time

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CPU times: user 12.6 ms, sys: 681 µs, total: 13.2 ms
Wall time: 840 ms

In [ ]:
%%time

!pip install sqlalchemy
!pip install tqdm
!pip install sentence_transformers
!pip install catboost
!pip install -U "sentence-transformers[train]"

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.32)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.0.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.66.5)
Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.10/dist-packages (3.0.1)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.42.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (2.3.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.3.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.23.5)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (12.1.105)
Requirement already satisfied: triton==2.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (2.3.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence_transformers) (12.6.20)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (2024.5.15)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.19.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (2.1.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (9.0.0)
Requirement already satisfied: sentence-transformers[train] in /usr/local/lib/python3.10/dist-packages (3.0.1)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (4.42.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (2.3.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (1.3.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (0.23.5)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (9.4.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (2.21.0)
Requirement already satisfied: accelerate>=0.20.3 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers[train]) (0.32.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.20.3->sentence-transformers[train]) (24.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.20.3->sentence-transformers[train]) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.20.3->sentence-transformers[train]) (6.0.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.20.3->sentence-transformers[train]) (0.4.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers[train]) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers[train]) (2024.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers[train]) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers[train]) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (1.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (12.1.105)
Requirement already satisfied: triton==2.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers[train]) (2.3.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence-transformers[train]) (12.6.20)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers[train]) (2024.5.15)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers[train]) (0.19.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (2.1.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (0.70.16)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->sentence-transformers[train]) (3.10.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers[train]) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers[train]) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (2.3.5)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->sentence-transformers[train]) (4.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers[train]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers[train]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers[train]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers[train]) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers[train]) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->sentence-transformers[train]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->sentence-transformers[train]) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->sentence-transformers[train]) (2024.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers[train]) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->sentence-transformers[train]) (1.16.0)
CPU times: user 235 ms, sys: 37.4 ms, total: 272 ms
Wall time: 31.3 s

In [ ]:
%%time

import os
os.chdir('drive/MyDrive')
# check if directory YT exists
if not os.path.exists('YT'):
  # create directory YT
  os.makedirs('YT')
# change directory to YT
os.chdir('YT')
if not os.path.exists('data'):
  # create directory data
  os.makedirs('data')
if not os.path.exists('models'):
  # create directory models
  os.makedirs('models')
os.chdir('models')
if not os.path.exists('embeddings'):
  # create directory embeddings
  os.makedirs('embeddings')
if not os.path.exists('estimators'):
  # create directory estimators
  os.makedirs('estimators')
os.chdir('..')

CPU times: user 1.32 ms, sys: 46 µs, total: 1.36 ms
Wall time: 3.61 ms

In [ ]:
# Load data

%%time

from sqlalchemy import create_engine
import pandas as pd

db_name = 'need_for_speed_30D'

# Create a sqlite engine instance
engine = create_engine(f"sqlite:///data/{db_name}.db")

# Read the database as a dataframe
raw_df = pd.read_sql_table('video_statistics', engine)

CPU times: user 15.9 s, sys: 4.4 s, total: 20.3 s
Wall time: 44 s

# Full MiniLM (Custom)

* MinMax Scale by channel

* Use full dataset

* Create custom embeddings from MiniLM

In [ ]:
# Preprocess data

%%time

from tqdm.notebook import tqdm
tqdm.pandas

from sklearn.preprocessing import MinMaxScaler

group_data = []
for name, group in tqdm(raw_df.groupby('channel_id')):
  if len(group) > 1:
    scaler = MinMaxScaler()
    row_data = group['video_view_count'].values.reshape(-1, 1)
    group['video_view_count'] = scaler.fit_transform(row_data)
    group_data.append(group)

  0%|          | 0/1652 [00:00<?, ?it/s]

CPU times: user 4.36 s, sys: 266 ms, total: 4.62 s
Wall time: 7.33 s

In [ ]:
# Split data

%%time

df = pd.concat(group_data).dropna(subset=['video_view_count'])

my_channel_title = 'Mitchell Diedrich'
my_df = df[df['channel_title'] == my_channel_title]
df = df[df['channel_title'] != my_channel_title]

if (captioned_only := False):
  df = df[df['video_caption']==True]
if (sample := False):
  df = df.sample(frac=0.1)

from sklearn.model_selection import train_test_split

train_df, val_test_df = train_test_split(df, test_size=0.2, random_state=42)
val_df, test_df = train_test_split(val_test_df, test_size=0.5, random_state=42)

train_df.shape, val_df.shape, test_df.shape, my_df.shape

CPU times: user 6.32 s, sys: 624 ms, total: 6.94 s
Wall time: 11.5 s

((920410, 14), (115051, 14), (115052, 14), (15, 14))

In [ ]:
%%time

# import pandas as pd
# from sentence_transformers import SentenceTransformer, InputExample, losses
# from torch.utils.data import DataLoader

# titles = train_df['video_title'].to_numpy()
# views = train_df['video_view_count'].to_numpy()

# views.shape

import pandas as pd
from sentence_transformers import SentenceTransformer
import torch
import torch.nn as nn

# Assuming you have your data as a DataFrame
titles = train_df['video_title'].to_numpy()
views = train_df['video_view_count'].to_numpy()

# Prepare data
data = pd.DataFrame({
    'title': titles,
    'views': views
})

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# use roberta
# model_name = 'all-roberta-large-v1'
model_name = 'all-MiniLM-L6-v2'

# Load SentenceTransformer model
base_model = SentenceTransformer(model_name)

# Define a regression model
class RegressionModel(nn.Module):
    def __init__(self, transformer_model):
        super(RegressionModel, self).__init__()
        self.transformer = transformer_model
        try:
          self.regressor = nn.Linear(384, 1)  # Change embedding size to 384
        except:
          self.regressor = nn.Linear(1024, 1)  # Change embedding size to 1024

    def forward(self, texts):
        # SentenceTransformer requires tokenized inputs
        embeddings = self.transformer.encode(texts, convert_to_tensor=True, show_progress_bar=True).to(device)
        # Pass the embeddings through the regression layer to predict views
        output = self.regressor(embeddings)
        return output

# Instantiate the regression model
model = RegressionModel(base_model).to(device)

if (load := True):
  model.load_state_dict(torch.load(f'models/embeddings/{model_name}_{db_name}_custom_model.pt'))
else:
  # Define loss function and optimizer
  criterion = nn.MSELoss().to(device)
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

  # Convert titles to embeddings and views to tensors
  train_titles = [row['title'] for index, row in data.iterrows()]
  train_views = torch.tensor(data['views'].values, dtype=torch.float32).unsqueeze(1).to(device)  # Reshape to (batch_size, 1)

  # Train the model
  model.train()
  for epoch in range(1):
      optimizer.zero_grad()

      # Forward pass
      predictions = model(train_titles)

      # Compute loss
      loss = criterion(predictions, train_views)

      # Backward pass and optimization
      loss.backward()
      optimizer.step()

      print(f"Epoch {epoch+1}, Loss: {loss.item()}")

  # save model as embedding model

  torch.save(model.state_dict(), f'models/embeddings/{model_name}_{db_name}_custom_model.pt')

  print("Training complete.")

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

CPU times: user 7.9 s, sys: 1.78 s, total: 9.68 s
Wall time: 20.4 s

In [ ]:
%%time

import numpy as np
from sentence_transformers import SentenceTransformer

if (load := True):
  train_embeddings = np.load(f'models/embeddings/train_embeddings_custom.npy',
                           allow_pickle=True)
  val_embeddings = np.load(f'models/embeddings/val_embeddings_custom.npy',
                          allow_pickle=True)
  test_embeddings = np.load(f'models/embeddings/test_embeddings_custom.npy',
                            allow_pickle=True)
  my_embeddings = np.load(f'models/embeddings/my_embeddings_custom.npy',
                          allow_pickle=True)
else:
  size = 4
  # Extract embeddings (using only the transformer part of your model)
  with torch.no_grad():
    train_embeddings = model.transformer.encode(
        titles,
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    val_embeddings = model.transformer.encode(
        val_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    test_embeddings = model.transformer.encode(
        test_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    my_embeddings = model.transformer.encode(
        my_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)

  # convert train_embeddings to np array
  train_embeddings = train_embeddings.cpu().numpy()
  val_embeddings = val_embeddings.cpu().numpy()
  test_embeddings = test_embeddings.cpu().numpy()
  my_embeddings = my_embeddings.cpu().numpy()

  import numpy as np
  # write embeddings to files
  np.save(f'models/embeddings/train_embeddings_custom.npy', train_embeddings)
  np.save(f'models/embeddings/val_embeddings_custom.npy', val_embeddings)
  np.save(f'models/embeddings/test_embeddings_custom.npy', test_embeddings)
  np.save(f'models/embeddings/my_embeddings_custom.npy', my_embeddings)

train_embeddings.shape, val_embeddings.shape, test_embeddings.shape, my_embeddings.shape

CPU times: user 1.8 ms, sys: 3.94 s, total: 3.94 s
Wall time: 11.3 s

((920410, 384), (115051, 384), (115052, 384), (15, 384))

In [ ]:
# Fit model

%%time

pd.set_option('display.width', 1000)

from datetime import datetime as dt
from catboost import CatBoostRegressor, Pool
import time

y_train = train_df['video_view_count'].to_numpy()
y_val = val_df['video_view_count'].to_numpy()
y_test = test_df['video_view_count'].to_numpy()
y_my = my_df['video_view_count'].to_numpy()

train_pool = Pool(train_embeddings, y_train)
val_pool = Pool(val_embeddings, y_val)
test_pool = Pool(test_embeddings, y_test)
my_pool = Pool(my_embeddings, y_my)

start = time.time()

params = {
    'iterations': 8192,
    'depth': 8,
    'learning_rate': .1,
    'loss_function': 'RMSE',
    # 'l2_leaf_reg': 1000,
}

model = CatBoostRegressor(**params, random_seed=42, verbose=True, task_type='GPU')
model.fit(train_pool, eval_set=val_pool, verbose=True)

Streaming output truncated to the last 5000 lines.
3197:	learn: 0.0533865	test: 0.0633209	best: 0.0633209 (3197)	total: 2m 40s	remaining: 4m 10s
3198:	learn: 0.0533846	test: 0.0633199	best: 0.0633199 (3198)	total: 2m 40s	remaining: 4m 10s
3199:	learn: 0.0533821	test: 0.0633196	best: 0.0633196 (3199)	total: 2m 40s	remaining: 4m 10s
3200:	learn: 0.0533804	test: 0.0633195	best: 0.0633195 (3200)	total: 2m 40s	remaining: 4m 10s
3201:	learn: 0.0533774	test: 0.0633197	best: 0.0633195 (3200)	total: 2m 40s	remaining: 4m 10s
3202:	learn: 0.0533756	test: 0.0633197	best: 0.0633195 (3200)	total: 2m 40s	remaining: 4m 9s
3203:	learn: 0.0533733	test: 0.0633195	best: 0.0633195 (3200)	total: 2m 40s	remaining: 4m 9s
3204:	learn: 0.0533692	test: 0.0633173	best: 0.0633173 (3204)	total: 2m 40s	remaining: 4m 9s
3205:	learn: 0.0533665	test: 0.0633172	best: 0.0633172 (3205)	total: 2m 40s	remaining: 4m 9s
3206:	learn: 0.0533646	test: 0.0633167	best: 0.0633167 (3206)	total: 2m 40s	remaining: 4m 9s
3207:	learn: 0.0533623	test: 0.0633166	best: 0.0633166 (3207)	total: 2m 40s	remaining: 4m 9s
3208:	learn: 0.0533594	test: 0.0633164	best: 0.0633164 (3208)	total: 2m 40s	remaining: 4m 9s
3209:	learn: 0.0533577	test: 0.0633164	best: 0.0633164 (3209)	total: 2m 40s	remaining: 4m 9s
3210:	learn: 0.0533556	test: 0.0633162	best: 0.0633162 (3210)	total: 2m 40s	remaining: 4m 9s
3211:	learn: 0.0533525	test: 0.0633160	best: 0.0633160 (3211)	total: 2m 40s	remaining: 4m 9s
3212:	learn: 0.0533510	test: 0.0633161	best: 0.0633160 (3211)	total: 2m 40s	remaining: 4m 9s
3213:	learn: 0.0533487	test: 0.0633160	best: 0.0633160 (3213)	total: 2m 40s	remaining: 4m 9s
3214:	learn: 0.0533463	test: 0.0633156	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 9s
3215:	learn: 0.0533451	test: 0.0633156	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 9s
3216:	learn: 0.0533428	test: 0.0633159	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 9s
3217:	learn: 0.0533396	test: 0.0633160	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 9s
3218:	learn: 0.0533370	test: 0.0633156	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 8s
3219:	learn: 0.0533348	test: 0.0633158	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 8s
3220:	learn: 0.0533311	test: 0.0633160	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 8s
3221:	learn: 0.0533280	test: 0.0633161	best: 0.0633156 (3214)	total: 2m 41s	remaining: 4m 8s
3222:	learn: 0.0533258	test: 0.0633153	best: 0.0633153 (3222)	total: 2m 41s	remaining: 4m 8s
3223:	learn: 0.0533241	test: 0.0633153	best: 0.0633153 (3222)	total: 2m 41s	remaining: 4m 8s
3224:	learn: 0.0533221	test: 0.0633154	best: 0.0633153 (3222)	total: 2m 41s	remaining: 4m 8s
3225:	learn: 0.0533198	test: 0.0633152	best: 0.0633152 (3225)	total: 2m 41s	remaining: 4m 8s
3226:	learn: 0.0533172	test: 0.0633154	best: 0.0633152 (3225)	total: 2m 41s	remaining: 4m 8s
3227:	learn: 0.0533157	test: 0.0633153	best: 0.0633152 (3225)	total: 2m 41s	remaining: 4m 8s
3228:	learn: 0.0533129	test: 0.0633150	best: 0.0633150 (3228)	total: 2m 41s	remaining: 4m 8s
3229:	learn: 0.0533103	test: 0.0633149	best: 0.0633149 (3229)	total: 2m 41s	remaining: 4m 8s
3230:	learn: 0.0533077	test: 0.0633149	best: 0.0633149 (3229)	total: 2m 41s	remaining: 4m 8s
3231:	learn: 0.0533055	test: 0.0633146	best: 0.0633146 (3231)	total: 2m 41s	remaining: 4m 8s
3232:	learn: 0.0533036	test: 0.0633150	best: 0.0633146 (3231)	total: 2m 41s	remaining: 4m 8s
3233:	learn: 0.0533017	test: 0.0633152	best: 0.0633146 (3231)	total: 2m 41s	remaining: 4m 7s
3234:	learn: 0.0532993	test: 0.0633151	best: 0.0633146 (3231)	total: 2m 41s	remaining: 4m 7s
3235:	learn: 0.0532969	test: 0.0633146	best: 0.0633146 (3235)	total: 2m 41s	remaining: 4m 7s
3236:	learn: 0.0532946	test: 0.0633142	best: 0.0633142 (3236)	total: 2m 41s	remaining: 4m 7s
3237:	learn: 0.0532925	test: 0.0633140	best: 0.0633140 (3237)	total: 2m 41s	remaining: 4m 7s
3238:	learn: 0.0532907	test: 0.0633142	best: 0.0633140 (3237)	total: 2m 41s	remaining: 4m 7s
3239:	learn: 0.0532885	test: 0.0633143	best: 0.0633140 (3237)	total: 2m 41s	remaining: 4m 7s
3240:	learn: 0.0532857	test: 0.0633142	best: 0.0633140 (3237)	total: 2m 42s	remaining: 4m 7s
3241:	learn: 0.0532831	test: 0.0633142	best: 0.0633140 (3237)	total: 2m 42s	remaining: 4m 7s
3242:	learn: 0.0532811	test: 0.0633142	best: 0.0633140 (3237)	total: 2m 42s	remaining: 4m 7s
3243:	learn: 0.0532781	test: 0.0633141	best: 0.0633140 (3237)	total: 2m 42s	remaining: 4m 7s
3244:	learn: 0.0532762	test: 0.0633136	best: 0.0633136 (3244)	total: 2m 42s	remaining: 4m 7s
3245:	learn: 0.0532744	test: 0.0633137	best: 0.0633136 (3244)	total: 2m 42s	remaining: 4m 7s
3246:	learn: 0.0532724	test: 0.0633139	best: 0.0633136 (3244)	total: 2m 42s	remaining: 4m 7s
3247:	learn: 0.0532701	test: 0.0633134	best: 0.0633134 (3247)	total: 2m 42s	remaining: 4m 7s
3248:	learn: 0.0532679	test: 0.0633127	best: 0.0633127 (3248)	total: 2m 42s	remaining: 4m 7s
3249:	learn: 0.0532661	test: 0.0633127	best: 0.0633127 (3248)	total: 2m 42s	remaining: 4m 6s
3250:	learn: 0.0532625	test: 0.0633129	best: 0.0633127 (3248)	total: 2m 42s	remaining: 4m 6s
3251:	learn: 0.0532603	test: 0.0633126	best: 0.0633126 (3251)	total: 2m 42s	remaining: 4m 6s
3252:	learn: 0.0532574	test: 0.0633123	best: 0.0633123 (3252)	total: 2m 42s	remaining: 4m 6s
3253:	learn: 0.0532558	test: 0.0633125	best: 0.0633123 (3252)	total: 2m 42s	remaining: 4m 6s
3254:	learn: 0.0532542	test: 0.0633125	best: 0.0633123 (3252)	total: 2m 42s	remaining: 4m 6s
3255:	learn: 0.0532513	test: 0.0633121	best: 0.0633121 (3255)	total: 2m 42s	remaining: 4m 6s
3256:	learn: 0.0532485	test: 0.0633121	best: 0.0633121 (3255)	total: 2m 42s	remaining: 4m 6s
3257:	learn: 0.0532461	test: 0.0633112	best: 0.0633112 (3257)	total: 2m 42s	remaining: 4m 6s
3258:	learn: 0.0532420	test: 0.0633097	best: 0.0633097 (3258)	total: 2m 42s	remaining: 4m 6s
3259:	learn: 0.0532398	test: 0.0633098	best: 0.0633097 (3258)	total: 2m 42s	remaining: 4m 6s
3260:	learn: 0.0532376	test: 0.0633096	best: 0.0633096 (3260)	total: 2m 42s	remaining: 4m 6s
3261:	learn: 0.0532354	test: 0.0633096	best: 0.0633096 (3261)	total: 2m 42s	remaining: 4m 6s
3262:	learn: 0.0532315	test: 0.0633094	best: 0.0633094 (3262)	total: 2m 42s	remaining: 4m 6s
3263:	learn: 0.0532284	test: 0.0633098	best: 0.0633094 (3262)	total: 2m 43s	remaining: 4m 6s
3264:	learn: 0.0532248	test: 0.0633099	best: 0.0633094 (3262)	total: 2m 43s	remaining: 4m 6s
3265:	learn: 0.0532223	test: 0.0633099	best: 0.0633094 (3262)	total: 2m 43s	remaining: 4m 6s
3266:	learn: 0.0532190	test: 0.0633100	best: 0.0633094 (3262)	total: 2m 43s	remaining: 4m 5s
3267:	learn: 0.0532164	test: 0.0633098	best: 0.0633094 (3262)	total: 2m 43s	remaining: 4m 5s
3268:	learn: 0.0532127	test: 0.0633079	best: 0.0633079 (3268)	total: 2m 43s	remaining: 4m 5s
3269:	learn: 0.0532103	test: 0.0633080	best: 0.0633079 (3268)	total: 2m 43s	remaining: 4m 5s
3270:	learn: 0.0532077	test: 0.0633081	best: 0.0633079 (3268)	total: 2m 43s	remaining: 4m 5s
3271:	learn: 0.0532056	test: 0.0633078	best: 0.0633078 (3271)	total: 2m 43s	remaining: 4m 5s
3272:	learn: 0.0532030	test: 0.0633078	best: 0.0633078 (3272)	total: 2m 43s	remaining: 4m 5s
3273:	learn: 0.0532007	test: 0.0633079	best: 0.0633078 (3272)	total: 2m 43s	remaining: 4m 5s
3274:	learn: 0.0531979	test: 0.0633077	best: 0.0633077 (3274)	total: 2m 43s	remaining: 4m 5s
3275:	learn: 0.0531954	test: 0.0633059	best: 0.0633059 (3275)	total: 2m 43s	remaining: 4m 5s
3276:	learn: 0.0531932	test: 0.0633059	best: 0.0633059 (3275)	total: 2m 43s	remaining: 4m 5s
3277:	learn: 0.0531897	test: 0.0633054	best: 0.0633054 (3277)	total: 2m 43s	remaining: 4m 5s
3278:	learn: 0.0531881	test: 0.0633053	best: 0.0633053 (3278)	total: 2m 43s	remaining: 4m 5s
3279:	learn: 0.0531859	test: 0.0633052	best: 0.0633052 (3279)	total: 2m 43s	remaining: 4m 5s
3280:	learn: 0.0531841	test: 0.0633053	best: 0.0633052 (3279)	total: 2m 43s	remaining: 4m 5s
3281:	learn: 0.0531812	test: 0.0633054	best: 0.0633052 (3279)	total: 2m 43s	remaining: 4m 5s
3282:	learn: 0.0531784	test: 0.0633053	best: 0.0633052 (3279)	total: 2m 43s	remaining: 4m 5s
3283:	learn: 0.0531720	test: 0.0633047	best: 0.0633047 (3283)	total: 2m 43s	remaining: 4m 4s
3284:	learn: 0.0531702	test: 0.0633044	best: 0.0633044 (3284)	total: 2m 43s	remaining: 4m 4s
3285:	learn: 0.0531669	test: 0.0633031	best: 0.0633031 (3285)	total: 2m 44s	remaining: 4m 4s
3286:	learn: 0.0531645	test: 0.0633031	best: 0.0633031 (3286)	total: 2m 44s	remaining: 4m 4s
3287:	learn: 0.0531627	test: 0.0633024	best: 0.0633024 (3287)	total: 2m 44s	remaining: 4m 4s
3288:	learn: 0.0531609	test: 0.0633023	best: 0.0633023 (3288)	total: 2m 44s	remaining: 4m 4s
3289:	learn: 0.0531583	test: 0.0632996	best: 0.0632996 (3289)	total: 2m 44s	remaining: 4m 4s
3290:	learn: 0.0531528	test: 0.0632973	best: 0.0632973 (3290)	total: 2m 44s	remaining: 4m 4s
3291:	learn: 0.0531508	test: 0.0632976	best: 0.0632973 (3290)	total: 2m 44s	remaining: 4m 4s
3292:	learn: 0.0531486	test: 0.0632951	best: 0.0632951 (3292)	total: 2m 44s	remaining: 4m 4s
3293:	learn: 0.0531450	test: 0.0632944	best: 0.0632944 (3293)	total: 2m 44s	remaining: 4m 4s
3294:	learn: 0.0531409	test: 0.0632950	best: 0.0632944 (3293)	total: 2m 44s	remaining: 4m 4s
3295:	learn: 0.0531383	test: 0.0632952	best: 0.0632944 (3293)	total: 2m 44s	remaining: 4m 4s
3296:	learn: 0.0531361	test: 0.0632951	best: 0.0632944 (3293)	total: 2m 44s	remaining: 4m 4s
3297:	learn: 0.0531330	test: 0.0632935	best: 0.0632935 (3297)	total: 2m 44s	remaining: 4m 4s
3298:	learn: 0.0531307	test: 0.0632927	best: 0.0632927 (3298)	total: 2m 44s	remaining: 4m 4s
3299:	learn: 0.0531271	test: 0.0632926	best: 0.0632926 (3299)	total: 2m 44s	remaining: 4m 4s
3300:	learn: 0.0531243	test: 0.0632925	best: 0.0632925 (3300)	total: 2m 44s	remaining: 4m 3s
3301:	learn: 0.0531218	test: 0.0632926	best: 0.0632925 (3300)	total: 2m 44s	remaining: 4m 3s
3302:	learn: 0.0531195	test: 0.0632921	best: 0.0632921 (3302)	total: 2m 44s	remaining: 4m 3s
3303:	learn: 0.0531168	test: 0.0632909	best: 0.0632909 (3303)	total: 2m 44s	remaining: 4m 3s
3304:	learn: 0.0531153	test: 0.0632910	best: 0.0632909 (3303)	total: 2m 44s	remaining: 4m 3s
3305:	learn: 0.0531129	test: 0.0632908	best: 0.0632908 (3305)	total: 2m 44s	remaining: 4m 3s
3306:	learn: 0.0531108	test: 0.0632909	best: 0.0632908 (3305)	total: 2m 44s	remaining: 4m 3s
3307:	learn: 0.0531081	test: 0.0632905	best: 0.0632905 (3307)	total: 2m 44s	remaining: 4m 3s
3308:	learn: 0.0531036	test: 0.0632898	best: 0.0632898 (3308)	total: 2m 44s	remaining: 4m 3s
3309:	learn: 0.0531004	test: 0.0632887	best: 0.0632887 (3309)	total: 2m 45s	remaining: 4m 3s
3310:	learn: 0.0530972	test: 0.0632888	best: 0.0632887 (3309)	total: 2m 45s	remaining: 4m 3s
3311:	learn: 0.0530943	test: 0.0632875	best: 0.0632875 (3311)	total: 2m 45s	remaining: 4m 3s
3312:	learn: 0.0530898	test: 0.0632878	best: 0.0632875 (3311)	total: 2m 45s	remaining: 4m 3s
3313:	learn: 0.0530880	test: 0.0632875	best: 0.0632875 (3313)	total: 2m 45s	remaining: 4m 3s
3314:	learn: 0.0530858	test: 0.0632869	best: 0.0632869 (3314)	total: 2m 45s	remaining: 4m 3s
3315:	learn: 0.0530835	test: 0.0632867	best: 0.0632867 (3315)	total: 2m 45s	remaining: 4m 3s
3316:	learn: 0.0530813	test: 0.0632866	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3317:	learn: 0.0530775	test: 0.0632877	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3318:	learn: 0.0530756	test: 0.0632880	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3319:	learn: 0.0530729	test: 0.0632874	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3320:	learn: 0.0530707	test: 0.0632872	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3321:	learn: 0.0530683	test: 0.0632874	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3322:	learn: 0.0530650	test: 0.0632869	best: 0.0632866 (3316)	total: 2m 45s	remaining: 4m 2s
3323:	learn: 0.0530628	test: 0.0632864	best: 0.0632864 (3323)	total: 2m 45s	remaining: 4m 2s
3324:	learn: 0.0530600	test: 0.0632857	best: 0.0632857 (3324)	total: 2m 45s	remaining: 4m 2s
3325:	learn: 0.0530586	test: 0.0632858	best: 0.0632857 (3324)	total: 2m 45s	remaining: 4m 2s
3326:	learn: 0.0530561	test: 0.0632851	best: 0.0632851 (3326)	total: 2m 45s	remaining: 4m 2s
3327:	learn: 0.0530526	test: 0.0632848	best: 0.0632848 (3327)	total: 2m 45s	remaining: 4m 2s
3328:	learn: 0.0530500	test: 0.0632849	best: 0.0632848 (3327)	total: 2m 45s	remaining: 4m 2s
3329:	learn: 0.0530465	test: 0.0632847	best: 0.0632847 (3329)	total: 2m 45s	remaining: 4m 2s
3330:	learn: 0.0530429	test: 0.0632832	best: 0.0632832 (3330)	total: 2m 46s	remaining: 4m 2s
3331:	learn: 0.0530408	test: 0.0632838	best: 0.0632832 (3330)	total: 2m 46s	remaining: 4m 2s
3332:	learn: 0.0530365	test: 0.0632831	best: 0.0632831 (3332)	total: 2m 46s	remaining: 4m 2s
3333:	learn: 0.0530335	test: 0.0632824	best: 0.0632824 (3333)	total: 2m 46s	remaining: 4m 2s
3334:	learn: 0.0530288	test: 0.0632795	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3335:	learn: 0.0530271	test: 0.0632797	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3336:	learn: 0.0530243	test: 0.0632800	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3337:	learn: 0.0530225	test: 0.0632802	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3338:	learn: 0.0530193	test: 0.0632798	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3339:	learn: 0.0530169	test: 0.0632799	best: 0.0632795 (3334)	total: 2m 46s	remaining: 4m 2s
3340:	learn: 0.0530147	test: 0.0632790	best: 0.0632790 (3340)	total: 2m 46s	remaining: 4m 2s
3341:	learn: 0.0530120	test: 0.0632783	best: 0.0632783 (3341)	total: 2m 46s	remaining: 4m 2s
3342:	learn: 0.0530096	test: 0.0632785	best: 0.0632783 (3341)	total: 2m 46s	remaining: 4m 2s
3343:	learn: 0.0530074	test: 0.0632777	best: 0.0632777 (3343)	total: 2m 46s	remaining: 4m 2s
3344:	learn: 0.0530052	test: 0.0632773	best: 0.0632773 (3344)	total: 2m 46s	remaining: 4m 1s
3345:	learn: 0.0530028	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3346:	learn: 0.0530002	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3347:	learn: 0.0529972	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3348:	learn: 0.0529947	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3349:	learn: 0.0529903	test: 0.0632780	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3350:	learn: 0.0529883	test: 0.0632782	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3351:	learn: 0.0529863	test: 0.0632781	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3352:	learn: 0.0529838	test: 0.0632782	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3353:	learn: 0.0529810	test: 0.0632777	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3354:	learn: 0.0529793	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3355:	learn: 0.0529771	test: 0.0632775	best: 0.0632773 (3344)	total: 2m 47s	remaining: 4m 1s
3356:	learn: 0.0529745	test: 0.0632773	best: 0.0632773 (3356)	total: 2m 47s	remaining: 4m 1s
3357:	learn: 0.0529718	test: 0.0632770	best: 0.0632770 (3357)	total: 2m 47s	remaining: 4m 1s
3358:	learn: 0.0529687	test: 0.0632774	best: 0.0632770 (3357)	total: 2m 47s	remaining: 4m 1s
3359:	learn: 0.0529651	test: 0.0632776	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3360:	learn: 0.0529625	test: 0.0632774	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3361:	learn: 0.0529604	test: 0.0632772	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3362:	learn: 0.0529580	test: 0.0632777	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3363:	learn: 0.0529555	test: 0.0632775	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3364:	learn: 0.0529543	test: 0.0632773	best: 0.0632770 (3357)	total: 2m 48s	remaining: 4m 1s
3365:	learn: 0.0529522	test: 0.0632770	best: 0.0632770 (3365)	total: 2m 48s	remaining: 4m 1s
3366:	learn: 0.0529504	test: 0.0632760	best: 0.0632760 (3366)	total: 2m 48s	remaining: 4m 1s
3367:	learn: 0.0529480	test: 0.0632746	best: 0.0632746 (3367)	total: 2m 48s	remaining: 4m 1s
3368:	learn: 0.0529461	test: 0.0632748	best: 0.0632746 (3367)	total: 2m 48s	remaining: 4m 1s
3369:	learn: 0.0529436	test: 0.0632743	best: 0.0632743 (3369)	total: 2m 48s	remaining: 4m 1s
3370:	learn: 0.0529404	test: 0.0632742	best: 0.0632742 (3370)	total: 2m 48s	remaining: 4m 1s
3371:	learn: 0.0529382	test: 0.0632744	best: 0.0632742 (3370)	total: 2m 48s	remaining: 4m 1s
3372:	learn: 0.0529350	test: 0.0632739	best: 0.0632739 (3372)	total: 2m 48s	remaining: 4m 1s
3373:	learn: 0.0529327	test: 0.0632738	best: 0.0632738 (3373)	total: 2m 48s	remaining: 4m 1s
3374:	learn: 0.0529294	test: 0.0632740	best: 0.0632738 (3373)	total: 2m 49s	remaining: 4m 1s
3375:	learn: 0.0529265	test: 0.0632738	best: 0.0632738 (3375)	total: 2m 49s	remaining: 4m 1s
3376:	learn: 0.0529238	test: 0.0632734	best: 0.0632734 (3376)	total: 2m 49s	remaining: 4m 1s
3377:	learn: 0.0529210	test: 0.0632739	best: 0.0632734 (3376)	total: 2m 49s	remaining: 4m 1s
3378:	learn: 0.0529192	test: 0.0632738	best: 0.0632734 (3376)	total: 2m 49s	remaining: 4m 1s
3379:	learn: 0.0529171	test: 0.0632736	best: 0.0632734 (3376)	total: 2m 49s	remaining: 4m 1s
3380:	learn: 0.0529133	test: 0.0632729	best: 0.0632729 (3380)	total: 2m 49s	remaining: 4m 1s
3381:	learn: 0.0529109	test: 0.0632729	best: 0.0632729 (3381)	total: 2m 49s	remaining: 4m 1s
3382:	learn: 0.0529091	test: 0.0632715	best: 0.0632715 (3382)	total: 2m 49s	remaining: 4m 1s
3383:	learn: 0.0529065	test: 0.0632715	best: 0.0632715 (3383)	total: 2m 49s	remaining: 4m 1s
3384:	learn: 0.0529044	test: 0.0632714	best: 0.0632714 (3384)	total: 2m 49s	remaining: 4m 1s
3385:	learn: 0.0529004	test: 0.0632699	best: 0.0632699 (3385)	total: 2m 49s	remaining: 4m 1s
3386:	learn: 0.0528984	test: 0.0632697	best: 0.0632697 (3386)	total: 2m 49s	remaining: 4m 1s
3387:	learn: 0.0528963	test: 0.0632695	best: 0.0632695 (3387)	total: 2m 50s	remaining: 4m 1s
3388:	learn: 0.0528939	test: 0.0632691	best: 0.0632691 (3388)	total: 2m 50s	remaining: 4m 1s
3389:	learn: 0.0528910	test: 0.0632682	best: 0.0632682 (3389)	total: 2m 50s	remaining: 4m 1s
3390:	learn: 0.0528889	test: 0.0632677	best: 0.0632677 (3390)	total: 2m 50s	remaining: 4m 1s
3391:	learn: 0.0528860	test: 0.0632672	best: 0.0632672 (3391)	total: 2m 50s	remaining: 4m
3392:	learn: 0.0528814	test: 0.0632651	best: 0.0632651 (3392)	total: 2m 50s	remaining: 4m
3393:	learn: 0.0528779	test: 0.0632646	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3394:	learn: 0.0528756	test: 0.0632650	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3395:	learn: 0.0528715	test: 0.0632648	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3396:	learn: 0.0528694	test: 0.0632649	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3397:	learn: 0.0528665	test: 0.0632652	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3398:	learn: 0.0528648	test: 0.0632650	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3399:	learn: 0.0528609	test: 0.0632646	best: 0.0632646 (3393)	total: 2m 50s	remaining: 4m
3400:	learn: 0.0528584	test: 0.0632636	best: 0.0632636 (3400)	total: 2m 50s	remaining: 4m
3401:	learn: 0.0528557	test: 0.0632634	best: 0.0632634 (3401)	total: 2m 50s	remaining: 4m
3402:	learn: 0.0528534	test: 0.0632634	best: 0.0632634 (3401)	total: 2m 50s	remaining: 4m
3403:	learn: 0.0528504	test: 0.0632633	best: 0.0632633 (3403)	total: 2m 50s	remaining: 4m
3404:	learn: 0.0528474	test: 0.0632634	best: 0.0632633 (3403)	total: 2m 51s	remaining: 4m
3405:	learn: 0.0528455	test: 0.0632629	best: 0.0632629 (3405)	total: 2m 51s	remaining: 4m
3406:	learn: 0.0528431	test: 0.0632622	best: 0.0632622 (3406)	total: 2m 51s	remaining: 4m
3407:	learn: 0.0528407	test: 0.0632619	best: 0.0632619 (3407)	total: 2m 51s	remaining: 4m
3408:	learn: 0.0528387	test: 0.0632592	best: 0.0632592 (3408)	total: 2m 51s	remaining: 4m
3409:	learn: 0.0528369	test: 0.0632593	best: 0.0632592 (3408)	total: 2m 51s	remaining: 4m
3410:	learn: 0.0528341	test: 0.0632591	best: 0.0632591 (3410)	total: 2m 51s	remaining: 4m
3411:	learn: 0.0528321	test: 0.0632593	best: 0.0632591 (3410)	total: 2m 51s	remaining: 3m 59s

In [ ]:
meta_params = {'timestamp': dt.now().strftime('%Y-%m-%d %H:%M:%S'),
    'embeddings': model_name, 'db_name': db_name}
meta_params.update(params)
meta_params['best_iteration'] = model.best_iteration_

meta_params['train_loss'] = model.best_score_['learn'][params['loss_function']]
meta_params['val_loss'] = model.best_score_['validation'][params['loss_function']]
meta_params['test_loss'] = model.eval_metrics(test_pool, ['RMSE'])['RMSE'][-1]

meta_params['train_r2'] = model.score(train_embeddings, y_train)
meta_params['val_r2'] = model.score(val_embeddings, y_val)
meta_params['test_r2'] = model.score(test_embeddings, y_test)

end = time.time()
meta_params['time'] = end - start

run_results_file = 'run_results.csv'
run_results_df = (pd.read_csv('run_results.csv')
                  if os.path.exists(run_results_file)
                  else pd.DataFrame(columns=meta_params.keys()))
run_results_df.loc[len(run_results_df)] = meta_params
run_results_df.to_csv(run_results_file, index=False)
run_results_df = pd.read_csv(run_results_file)

# print 3 digits
pd.options.display.float_format = '{:.5f}'.format

print('Past Results')
print(run_results_df.sort_values(by='test_loss').head(16))
print()
print('This Run')
print(run_results_df.tail(1))

Past Results
              timestamp            embeddings             db_name  iterations  depth  learning_rate loss_function   l2_leaf_reg  best_iteration  train_loss  val_loss  test_loss  train_r2   val_r2  test_r2      time
10  2024-08-21 06:31:35  all-roberta-large-v1  need_for_speed_30D       16384      8        0.10000          RMSE    1000.00000           16244     0.04754   0.06613    0.06171   0.47546  0.07570  0.06185 765.58778
8   2024-08-21 06:10:51  all-roberta-large-v1  need_for_speed_30D        8192      6        0.10000          RMSE    1000.00000            8117     0.05620   0.06647    0.06182   0.26868  0.06614  0.05866 209.13300
9   2024-08-21 06:18:22  all-roberta-large-v1  need_for_speed_30D        8192      8        0.10000          RMSE    1000.00000            8168     0.05407   0.06629    0.06183   0.32379  0.07138  0.05825 415.64894
13  2024-08-21 06:53:00  all-roberta-large-v1  need_for_speed_30D        8192     10        0.25000          RMSE    1000.00000            7125     0.04112   0.06624    0.06195   0.57041  0.07263  0.05455 863.67315
7   2024-08-21 06:06:53  all-roberta-large-v1  need_for_speed_30D        8192      4        0.10000          RMSE    1000.00000            8187     0.05828   0.06657    0.06197   0.21510  0.06340  0.05386 171.43772
16  2024-08-21 17:00:54      all-MiniLM-L6-v2  need_for_speed_30D        8192      8        0.10000          RMSE           NaN            8189     0.04323   0.06262    0.06232   0.57382  0.11796  0.10898 581.08003
12  2024-08-21 06:37:59  all-roberta-large-v1  need_for_speed_30D        1024     10        0.10000          RMSE           NaN             974     0.03701   0.06671    0.06238   0.66938  0.05935  0.04158 134.64956
11  2024-08-21 06:34:41  all-roberta-large-v1  need_for_speed_30D        2048      8        0.10000          RMSE           NaN            1309     0.03244   0.06674    0.06258   0.63825  0.05872  0.03535 131.87342
6   2024-08-21 06:02:59  all-roberta-large-v1  need_for_speed_30D        8192      4        0.10000          RMSE 1000000.00000            8191     0.06458   0.06757    0.06279   0.03630  0.03494  0.02868 295.57950
5   2024-08-21 05:57:50  all-roberta-large-v1  need_for_speed_30D         256      4        0.10000          RMSE 1000000.00000             255     0.06563   0.06861    0.06357   0.00473  0.00511  0.00443  26.94997
4   2024-08-21 05:38:09  all-roberta-large-v1  need_for_speed_30D         256      4        0.10000          RMSE 1000000.00000               8     0.06578   0.06879    0.06371   0.00000 -0.00005 -0.00003  25.65228
15  2024-08-21 16:25:52      all-MiniLM-L6-v2  need_for_speed_30D        8192      2        0.10000          RMSE           NaN            8190     0.06289   0.06433    0.06375   0.09814  0.06902  0.06767 260.18066
14  2024-08-21 16:20:35      all-MiniLM-L6-v2  need_for_speed_30D        1024      2        0.10000          RMSE           NaN            1023     0.06455   0.06521    0.06456   0.04971  0.04337  0.04393  78.50528
1   2024-08-21 05:02:17  all-roberta-large-v1  need_for_speed_30D        1024      8        0.10000          RMSE     100.00000            1023     0.05945   0.06059    0.07056   0.17802  0.05247  0.04564  61.65980
2   2024-08-21 05:04:20  all-roberta-large-v1  need_for_speed_30D        1024      8        0.10000          RMSE    1000.00000            1023     0.06180   0.06062    0.07071   0.11178  0.05143  0.04174  85.28625
0   2024-08-21 05:00:45  all-roberta-large-v1  need_for_speed_30D         256      8        0.10000          RMSE     100.00000             255     0.06243   0.06088    0.07087   0.09354  0.04315  0.03737  62.72174

This Run
              timestamp        embeddings             db_name  iterations  depth  learning_rate loss_function  l2_leaf_reg  best_iteration  train_loss  val_loss  test_loss  train_r2  val_r2  test_r2      time
16  2024-08-21 17:00:54  all-MiniLM-L6-v2  need_for_speed_30D        8192      8        0.10000          RMSE          NaN            8189     0.04323   0.06262    0.06232   0.57382 0.11796  0.10898 581.08003

In [ ]:
# dont use scientific notation
pd.options.display.float_format = '{:.3f}'.format
# model = model.load_model(f'/data/models/{model_name}_{db_name}_model.cbm')
temp_my_df = my_df.copy()
temp_my_df['predicted_views'] = model.predict(my_pool)
print(model.score(my_pool))
temp_my_df = temp_my_df[['video_title', 'video_view_count', 'predicted_views']]
temp_my_df.sort_values(by='predicted_views', ascending=False)

-0.2572151879446589

                                              video_title  video_view_count  predicted_views
884329             Need for Speed: Carbon - Retrospective             1.000            0.090
884330        Need for Speed: Most Wanted - Retrospective             0.514            0.066
884325         Need for Speed: Undercover - Retrospective             0.390            0.043
884332                          Neon White is Stupid Good             0.006            0.030
884320                       Star Wars' New "Controversy"             0.000            0.029
884324      Need for Speed: Underground 2 - Retrospective             0.216            0.029
884333   The Only Honest Game About War; This War of Mine             0.007            0.027
884327                   Fallout: New Vegas Review (2024)             0.013            0.023
884326          Need for Speed: ProStreet - Retrospective             0.575            0.022
884323            Need for Speed: The Run - Retrospective             0.231            0.022
884322                  Trevor Philips Character Analysis             0.013            0.016
884321                                 Game Over, Comrade             0.003            0.014
884328          Dead Rising; The First Modern Zombie Game             0.094            0.014
884331                           I don't like Rollerdrome             0.007            0.014
884334  Is Any of This Real? Epistemology and Video Games             0.002            0.010

In [ ]:
# save model
model.save_model(f'models/{model_name}_{db_name}_model_31\.cbm')

In [ ]:
from openai import OpenAI
client = OpenAI()

response = client.embeddings.create(
    input="Your text string goes here",
    model="text-embedding-3-small"
)

print(response.data[0].embedding)

# Captioned MiniLM (Custom)

* MinMax Scale by channel

* Use full dataset

* Create custom embeddings from MiniLM

In [ ]:
# Input variables

load = True
captioned_only = True
sample = False

In [ ]:
# Preprocess data

%%time

from tqdm.notebook import tqdm
tqdm.pandas

from sklearn.preprocessing import MinMaxScaler

group_data = []
for name, group in tqdm(raw_df.groupby('channel_id')):
  if len(group) > 1:
    scaler = MinMaxScaler()
    row_data = group['video_view_count'].values.reshape(-1, 1)
    group['video_view_count'] = scaler.fit_transform(row_data)
    group_data.append(group)

  0%|          | 0/1652 [00:00<?, ?it/s]

CPU times: user 4.16 s, sys: 235 ms, total: 4.4 s
Wall time: 8.58 s

In [ ]:
# Split data

%%time

df = pd.concat(group_data).dropna(subset=['video_view_count'])

my_channel_title = 'Mitchell Diedrich'
my_df = df[df['channel_title'] == my_channel_title]
df = df[df['channel_title'] != my_channel_title]

if captioned_only:
  df = df[df['video_caption']==True]
if sample:
  df = df.sample(frac=0.1)

from sklearn.model_selection import train_test_split

train_df, val_test_df = train_test_split(df, test_size=0.2, random_state=42)
val_df, test_df = train_test_split(val_test_df, test_size=0.5, random_state=42)

train_df.shape, val_df.shape, test_df.shape, my_df.shape

CPU times: user 2.64 s, sys: 555 ms, total: 3.2 s
Wall time: 3.22 s

((16459, 14), (2057, 14), (2058, 14), (15, 14))

In [ ]:
%%time

import pandas as pd
from sentence_transformers import SentenceTransformer
import torch
import torch.nn as nn

# Assuming you have your data as a DataFrame
titles = train_df['video_title'].to_numpy()
views = train_df['video_view_count'].to_numpy()

# Prepare data
data = pd.DataFrame({
    'title': titles,
    'views': views
})

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# modelname
model_name = 'all-MiniLM-L6-v2'

# Load SentenceTransformer model
base_model = SentenceTransformer(model_name)

save_path = f'models/embeddings/captioned_minilm.pt'

# Define a regression model
class RegressionModel(nn.Module):
    def __init__(self, transformer_model):
        super(RegressionModel, self).__init__()
        self.transformer = transformer_model
        try:
          self.regressor = nn.Linear(384, 1)  # Change embedding size to 384
        except:
          self.regressor = nn.Linear(1024, 1)  # Change embedding size to 1024

    def forward(self, texts):
        # SentenceTransformer requires tokenized inputs
        embeddings = self.transformer.encode(texts, convert_to_tensor=True, show_progress_bar=True).to(device)
        # Pass the embeddings through the regression layer to predict views
        output = self.regressor(embeddings)
        return output

# Instantiate the regression model
model = RegressionModel(base_model).to(device)

if load:
  model.load_state_dict(torch.load(save_path))
else:
  # Define loss function and optimizer
  criterion = nn.MSELoss().to(device)
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

  # Convert titles to embeddings and views to tensors
  train_titles = [row['title'] for index, row in data.iterrows()]
  train_views = torch.tensor(data['views'].values, dtype=torch.float32).unsqueeze(1).to(device)  # Reshape to (batch_size, 1)

  # Train the model
  model.train()
  for epoch in range(1):
      optimizer.zero_grad()

      # Forward pass
      predictions = model(train_titles)

      # Compute loss
      loss = criterion(predictions, train_views)

      # Backward pass and optimization
      loss.backward()
      optimizer.step()

      print(f"Epoch {epoch+1}, Loss: {loss.item()}")

  # save model as embedding model

  torch.save(model.state_dict(), save_path)

  print("Training complete.")

CPU times: user 233 ms, sys: 163 ms, total: 396 ms
Wall time: 6.08 s

In [ ]:
%%time

import numpy as np
from sentence_transformers import SentenceTransformer

embeddings_name = '_embeddings_captioned_minilm_custom.npy'

if load:

  train_embeddings = np.load(f'models/embeddings/train{embeddings_name}',
                           allow_pickle=True)
  val_embeddings = np.load(f'models/embeddings/val{embeddings_name}',
                          allow_pickle=True)
  test_embeddings = np.load(f'models/embeddings/test{embeddings_name}',
                            allow_pickle=True)
  my_embeddings = np.load(f'models/embeddings/my{embeddings_name}',
                          allow_pickle=True)
else:
  size = 64
  # Extract embeddings (using only the transformer part of your model)
  with torch.no_grad():
    train_embeddings = model.transformer.encode(
        titles,
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    val_embeddings = model.transformer.encode(
        val_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    test_embeddings = model.transformer.encode(
        test_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)
    my_embeddings = model.transformer.encode(
        my_df['video_title'].to_numpy(),
        convert_to_tensor=True,
        show_progress_bar=True,
        batch_size=size
        ).to(device)

  # convert train_embeddings to np array
  train_embeddings = train_embeddings.cpu().numpy()
  val_embeddings = val_embeddings.cpu().numpy()
  test_embeddings = test_embeddings.cpu().numpy()
  my_embeddings = my_embeddings.cpu().numpy()

  import numpy as np
  # write embeddings to files
  np.save(f'models/embeddings/train{embeddings_name}', train_embeddings)
  np.save(f'models/embeddings/val{embeddings_name}', val_embeddings)
  np.save(f'models/embeddings/test{embeddings_name}', test_embeddings)
  np.save(f'models/embeddings/my{embeddings_name}', my_embeddings)

train_embeddings.shape, val_embeddings.shape, test_embeddings.shape, my_embeddings.shape

CPU times: user 18.2 ms, sys: 30 ms, total: 48.2 ms
Wall time: 3.03 s

((16459, 384), (2057, 384), (2058, 384), (15, 384))

In [ ]:
# Fit model

%%time

pd.set_option('display.width', 1000)

from datetime import datetime as dt
from catboost import CatBoostRegressor, Pool
import time

y_train = train_df['video_view_count'].to_numpy()
y_val = val_df['video_view_count'].to_numpy()
y_test = test_df['video_view_count'].to_numpy()
y_my = my_df['video_view_count'].to_numpy()

train_pool = Pool(train_embeddings, y_train)
val_pool = Pool(val_embeddings, y_val)
test_pool = Pool(test_embeddings, y_test)
my_pool = Pool(my_embeddings, y_my)

start = time.time()

params = {
    'iterations': 2048,
    'depth': 8,
    'learning_rate': .1,
    'loss_function': 'RMSE',
    'l2_leaf_reg': 100,
}

model = CatBoostRegressor(**params, random_seed=42, verbose=True, task_type='GPU')
model.fit(train_pool, eval_set=val_pool, verbose=True)

loss_data = {
    'train': model.eval_metrics(train_pool, ['RMSE'])['RMSE'][-1],
    'val': model.eval_metrics(val_pool, ['RMSE'])['RMSE'][-1],
    'test': model.eval_metrics(test_pool, ['RMSE'])['RMSE'][-1]
}
r2_data = {
    'train': model.score(train_embeddings, y_train),
    'val': model.score(val_embeddings, y_val),
    'test': model.score(test_embeddings, y_test)
}

loss_series = pd.Series(loss_data, name='loss')
r2_series = pd.Series(r2_data, name='r2')

eta_params = {'timestamp': dt.now().strftime('%Y-%m-%d %H:%M:%S'),
    'embeddings': model_name, 'db_name': db_name}
meta_params.update(params)
meta_params['best_iteration'] = model.best_iteration_

meta_params['train_loss'] = model.best_score_['learn'][params['loss_function']]
meta_params['val_loss'] = model.best_score_['validation'][params['loss_function']]
meta_params['test_loss'] = model.eval_metrics(test_pool, ['RMSE'])['RMSE'][-1]

meta_params['train_r2'] = model.score(train_embeddings, y_train)
meta_params['val_r2'] = model.score(val_embeddings, y_val)
meta_params['test_r2'] = model.score(test_embeddings, y_test)

end = time.time()
meta_params['time'] = end - start

run_results_file = 'captioned_minilm_run_results.csv'
run_results_df = (pd.read_csv(run_results_file)
                  if os.path.exists(run_results_file)
                  else pd.DataFrame(columns=meta_params.keys()))
run_results_df.loc[len(run_results_df)] = meta_params
run_results_df.to_csv(run_results_file, index=False)
run_results_df = pd.read_csv(run_results_file)

# print 3 digits
pd.options.display.float_format = '{:.5f}'.format

print('Past Results')
print(run_results_df.sort_values(by='test_loss').head(16))
print()

metrics_df = pd.concat([loss_series, r2_series], axis=1)
metrics_df.T

0:	learn: 0.0807856	test: 0.0930953	best: 0.0930953 (0)	total: 189ms	remaining: 6m 27s
1:	learn: 0.0802579	test: 0.0926788	best: 0.0926788 (1)	total: 330ms	remaining: 5m 37s
2:	learn: 0.0797277	test: 0.0922143	best: 0.0922143 (2)	total: 436ms	remaining: 4m 57s
3:	learn: 0.0793755	test: 0.0919102	best: 0.0919102 (3)	total: 530ms	remaining: 4m 31s
4:	learn: 0.0789341	test: 0.0915945	best: 0.0915945 (4)	total: 647ms	remaining: 4m 24s
5:	learn: 0.0785477	test: 0.0913046	best: 0.0913046 (5)	total: 760ms	remaining: 4m 18s
6:	learn: 0.0782199	test: 0.0910302	best: 0.0910302 (6)	total: 862ms	remaining: 4m 11s
7:	learn: 0.0778818	test: 0.0907804	best: 0.0907804 (7)	total: 965ms	remaining: 4m 6s
8:	learn: 0.0776941	test: 0.0905993	best: 0.0905993 (8)	total: 1.05s	remaining: 3m 58s
9:	learn: 0.0774304	test: 0.0904232	best: 0.0904232 (9)	total: 1.16s	remaining: 3m 55s
10:	learn: 0.0771025	test: 0.0902419	best: 0.0902419 (10)	total: 1.27s	remaining: 3m 56s
11:	learn: 0.0768017	test: 0.0900335	best: 0.0900335 (11)	total: 1.38s	remaining: 3m 54s
12:	learn: 0.0764963	test: 0.0898008	best: 0.0898008 (12)	total: 1.51s	remaining: 3m 56s
13:	learn: 0.0762912	test: 0.0896883	best: 0.0896883 (13)	total: 1.61s	remaining: 3m 53s
14:	learn: 0.0761445	test: 0.0895672	best: 0.0895672 (14)	total: 1.7s	remaining: 3m 50s
15:	learn: 0.0759553	test: 0.0893787	best: 0.0893787 (15)	total: 1.79s	remaining: 3m 47s
16:	learn: 0.0756934	test: 0.0891910	best: 0.0891910 (16)	total: 1.91s	remaining: 3m 48s
17:	learn: 0.0754771	test: 0.0890786	best: 0.0890786 (17)	total: 2.02s	remaining: 3m 48s
18:	learn: 0.0752475	test: 0.0888596	best: 0.0888596 (18)	total: 2.13s	remaining: 3m 47s
19:	learn: 0.0750230	test: 0.0886916	best: 0.0886916 (19)	total: 2.25s	remaining: 3m 48s
20:	learn: 0.0748629	test: 0.0886126	best: 0.0886126 (20)	total: 2.36s	remaining: 3m 47s
21:	learn: 0.0746173	test: 0.0884490	best: 0.0884490 (21)	total: 2.47s	remaining: 3m 47s
22:	learn: 0.0744728	test: 0.0883627	best: 0.0883627 (22)	total: 2.58s	remaining: 3m 46s
23:	learn: 0.0743010	test: 0.0882205	best: 0.0882205 (23)	total: 2.69s	remaining: 3m 46s
24:	learn: 0.0741283	test: 0.0880483	best: 0.0880483 (24)	total: 2.81s	remaining: 3m 47s
25:	learn: 0.0739557	test: 0.0879583	best: 0.0879583 (25)	total: 2.93s	remaining: 3m 48s
26:	learn: 0.0737996	test: 0.0878921	best: 0.0878921 (26)	total: 3.04s	remaining: 3m 47s
27:	learn: 0.0736172	test: 0.0877602	best: 0.0877602 (27)	total: 3.15s	remaining: 3m 47s
28:	learn: 0.0735714	test: 0.0877148	best: 0.0877148 (28)	total: 3.24s	remaining: 3m 45s
29:	learn: 0.0734358	test: 0.0876119	best: 0.0876119 (29)	total: 3.35s	remaining: 3m 45s
30:	learn: 0.0733105	test: 0.0875465	best: 0.0875465 (30)	total: 3.48s	remaining: 3m 46s
31:	learn: 0.0731675	test: 0.0874293	best: 0.0874293 (31)	total: 3.66s	remaining: 3m 50s
32:	learn: 0.0730836	test: 0.0873859	best: 0.0873859 (32)	total: 3.81s	remaining: 3m 52s
33:	learn: 0.0729306	test: 0.0872480	best: 0.0872480 (33)	total: 3.94s	remaining: 3m 53s
34:	learn: 0.0728680	test: 0.0872121	best: 0.0872121 (34)	total: 4.08s	remaining: 3m 54s
35:	learn: 0.0727326	test: 0.0871426	best: 0.0871426 (35)	total: 4.25s	remaining: 3m 57s
36:	learn: 0.0725863	test: 0.0870754	best: 0.0870754 (36)	total: 4.41s	remaining: 3m 59s
37:	learn: 0.0724685	test: 0.0869779	best: 0.0869779 (37)	total: 4.54s	remaining: 3m 59s
38:	learn: 0.0723295	test: 0.0868953	best: 0.0868953 (38)	total: 4.68s	remaining: 4m 1s
39:	learn: 0.0721934	test: 0.0868053	best: 0.0868053 (39)	total: 4.8s	remaining: 4m
40:	learn: 0.0720701	test: 0.0867804	best: 0.0867804 (40)	total: 4.96s	remaining: 4m 2s
41:	learn: 0.0719542	test: 0.0867319	best: 0.0867319 (41)	total: 5.13s	remaining: 4m 4s
42:	learn: 0.0718263	test: 0.0866274	best: 0.0866274 (42)	total: 5.29s	remaining: 4m 6s
43:	learn: 0.0717276	test: 0.0865574	best: 0.0865574 (43)	total: 5.44s	remaining: 4m 7s
44:	learn: 0.0717017	test: 0.0865406	best: 0.0865406 (44)	total: 5.58s	remaining: 4m 8s
45:	learn: 0.0715705	test: 0.0864748	best: 0.0864748 (45)	total: 5.75s	remaining: 4m 10s
46:	learn: 0.0714730	test: 0.0864111	best: 0.0864111 (46)	total: 5.93s	remaining: 4m 12s
47:	learn: 0.0713770	test: 0.0863915	best: 0.0863915 (47)	total: 6.11s	remaining: 4m 14s
48:	learn: 0.0712922	test: 0.0863346	best: 0.0863346 (48)	total: 6.27s	remaining: 4m 15s
49:	learn: 0.0712372	test: 0.0863117	best: 0.0863117 (49)	total: 6.41s	remaining: 4m 16s
50:	learn: 0.0711563	test: 0.0862881	best: 0.0862881 (50)	total: 6.58s	remaining: 4m 17s
51:	learn: 0.0710784	test: 0.0862457	best: 0.0862457 (51)	total: 6.73s	remaining: 4m 18s
52:	learn: 0.0710449	test: 0.0862374	best: 0.0862374 (52)	total: 6.88s	remaining: 4m 18s
53:	learn: 0.0709475	test: 0.0861654	best: 0.0861654 (53)	total: 7.06s	remaining: 4m 20s
54:	learn: 0.0708140	test: 0.0861511	best: 0.0861511 (54)	total: 7.23s	remaining: 4m 21s
55:	learn: 0.0707557	test: 0.0860897	best: 0.0860897 (55)	total: 7.37s	remaining: 4m 22s
56:	learn: 0.0707025	test: 0.0860834	best: 0.0860834 (56)	total: 7.46s	remaining: 4m 20s
57:	learn: 0.0706812	test: 0.0860671	best: 0.0860671 (57)	total: 7.55s	remaining: 4m 18s
58:	learn: 0.0705881	test: 0.0860142	best: 0.0860142 (58)	total: 7.66s	remaining: 4m 18s
59:	learn: 0.0704871	test: 0.0859851	best: 0.0859851 (59)	total: 7.77s	remaining: 4m 17s
60:	learn: 0.0704165	test: 0.0859301	best: 0.0859301 (60)	total: 7.88s	remaining: 4m 16s
61:	learn: 0.0703659	test: 0.0859245	best: 0.0859245 (61)	total: 7.97s	remaining: 4m 15s
62:	learn: 0.0702867	test: 0.0858660	best: 0.0858660 (62)	total: 8.08s	remaining: 4m 14s
63:	learn: 0.0702092	test: 0.0858222	best: 0.0858222 (63)	total: 8.2s	remaining: 4m 14s
64:	learn: 0.0701565	test: 0.0858142	best: 0.0858142 (64)	total: 8.29s	remaining: 4m 12s
65:	learn: 0.0701382	test: 0.0858088	best: 0.0858088 (65)	total: 8.38s	remaining: 4m 11s
66:	learn: 0.0700519	test: 0.0857697	best: 0.0857697 (66)	total: 8.5s	remaining: 4m 11s
67:	learn: 0.0700207	test: 0.0857560	best: 0.0857560 (67)	total: 8.58s	remaining: 4m 9s
68:	learn: 0.0699612	test: 0.0857416	best: 0.0857416 (68)	total: 8.68s	remaining: 4m 9s
69:	learn: 0.0698688	test: 0.0856956	best: 0.0856956 (69)	total: 8.79s	remaining: 4m 8s
70:	learn: 0.0698048	test: 0.0856624	best: 0.0856624 (70)	total: 8.91s	remaining: 4m 8s
71:	learn: 0.0696856	test: 0.0856090	best: 0.0856090 (71)	total: 9.03s	remaining: 4m 7s
72:	learn: 0.0696021	test: 0.0855529	best: 0.0855529 (72)	total: 9.14s	remaining: 4m 7s
73:	learn: 0.0695167	test: 0.0855189	best: 0.0855189 (73)	total: 9.25s	remaining: 4m 6s
74:	learn: 0.0694780	test: 0.0854844	best: 0.0854844 (74)	total: 9.35s	remaining: 4m 5s
75:	learn: 0.0693888	test: 0.0854669	best: 0.0854669 (75)	total: 9.47s	remaining: 4m 5s
76:	learn: 0.0693172	test: 0.0854327	best: 0.0854327 (76)	total: 9.57s	remaining: 4m 4s
77:	learn: 0.0692352	test: 0.0853856	best: 0.0853856 (77)	total: 9.68s	remaining: 4m 4s
78:	learn: 0.0692171	test: 0.0853810	best: 0.0853810 (78)	total: 9.76s	remaining: 4m 3s
79:	learn: 0.0691574	test: 0.0853629	best: 0.0853629 (79)	total: 9.86s	remaining: 4m 2s
80:	learn: 0.0691018	test: 0.0853511	best: 0.0853511 (80)	total: 9.97s	remaining: 4m 2s
81:	learn: 0.0690387	test: 0.0852764	best: 0.0852764 (81)	total: 10.1s	remaining: 4m 1s
82:	learn: 0.0690186	test: 0.0852701	best: 0.0852701 (82)	total: 10.1s	remaining: 4m
83:	learn: 0.0689643	test: 0.0852521	best: 0.0852521 (83)	total: 10.2s	remaining: 3m 59s
84:	learn: 0.0688651	test: 0.0852517	best: 0.0852517 (84)	total: 10.3s	remaining: 3m 58s
85:	learn: 0.0688345	test: 0.0852514	best: 0.0852514 (85)	total: 10.4s	remaining: 3m 57s
86:	learn: 0.0687100	test: 0.0852325	best: 0.0852325 (86)	total: 10.5s	remaining: 3m 57s
87:	learn: 0.0686063	test: 0.0851721	best: 0.0851721 (87)	total: 10.7s	remaining: 3m 57s
88:	learn: 0.0685484	test: 0.0851370	best: 0.0851370 (88)	total: 10.7s	remaining: 3m 56s
89:	learn: 0.0684932	test: 0.0850995	best: 0.0850995 (89)	total: 10.9s	remaining: 3m 56s
90:	learn: 0.0684417	test: 0.0850966	best: 0.0850966 (90)	total: 11s	remaining: 3m 55s
91:	learn: 0.0684050	test: 0.0850644	best: 0.0850644 (91)	total: 11.1s	remaining: 3m 54s
92:	learn: 0.0683215	test: 0.0850442	best: 0.0850442 (92)	total: 11.2s	remaining: 3m 54s
93:	learn: 0.0682403	test: 0.0850349	best: 0.0850349 (93)	total: 11.3s	remaining: 3m 54s
94:	learn: 0.0681628	test: 0.0850241	best: 0.0850241 (94)	total: 11.4s	remaining: 3m 53s
95:	learn: 0.0681126	test: 0.0850079	best: 0.0850079 (95)	total: 11.5s	remaining: 3m 53s
96:	learn: 0.0680538	test: 0.0850088	best: 0.0850079 (95)	total: 11.6s	remaining: 3m 52s
97:	learn: 0.0680040	test: 0.0849902	best: 0.0849902 (97)	total: 11.7s	remaining: 3m 52s
98:	learn: 0.0679793	test: 0.0849896	best: 0.0849896 (98)	total: 11.8s	remaining: 3m 51s
99:	learn: 0.0679228	test: 0.0849800	best: 0.0849800 (99)	total: 11.9s	remaining: 3m 51s
100:	learn: 0.0678574	test: 0.0849400	best: 0.0849400 (100)	total: 12s	remaining: 3m 50s
101:	learn: 0.0677995	test: 0.0849176	best: 0.0849176 (101)	total: 12.1s	remaining: 3m 50s
102:	learn: 0.0677729	test: 0.0849086	best: 0.0849086 (102)	total: 12.2s	remaining: 3m 49s
103:	learn: 0.0677262	test: 0.0848978	best: 0.0848978 (103)	total: 12.3s	remaining: 3m 49s
104:	learn: 0.0677006	test: 0.0848923	best: 0.0848923 (104)	total: 12.3s	remaining: 3m 48s
105:	learn: 0.0676465	test: 0.0848878	best: 0.0848878 (105)	total: 12.4s	remaining: 3m 48s
106:	learn: 0.0675531	test: 0.0848840	best: 0.0848840 (106)	total: 12.6s	remaining: 3m 47s
107:	learn: 0.0674860	test: 0.0848373	best: 0.0848373 (107)	total: 12.7s	remaining: 3m 47s
108:	learn: 0.0674108	test: 0.0848195	best: 0.0848195 (108)	total: 12.8s	remaining: 3m 47s
109:	learn: 0.0673150	test: 0.0847605	best: 0.0847605 (109)	total: 12.9s	remaining: 3m 47s
110:	learn: 0.0672466	test: 0.0847508	best: 0.0847508 (110)	total: 13s	remaining: 3m 47s
111:	learn: 0.0671829	test: 0.0847462	best: 0.0847462 (111)	total: 13.1s	remaining: 3m 46s
112:	learn: 0.0671381	test: 0.0847359	best: 0.0847359 (112)	total: 13.2s	remaining: 3m 46s
113:	learn: 0.0671006	test: 0.0847308	best: 0.0847308 (113)	total: 13.3s	remaining: 3m 46s
114:	learn: 0.0670034	test: 0.0846937	best: 0.0846937 (114)	total: 13.4s	remaining: 3m 45s
115:	learn: 0.0669565	test: 0.0846760	best: 0.0846760 (115)	total: 13.5s	remaining: 3m 45s
116:	learn: 0.0669176	test: 0.0846751	best: 0.0846751 (116)	total: 13.6s	remaining: 3m 44s
117:	learn: 0.0668942	test: 0.0846784	best: 0.0846751 (116)	total: 13.7s	remaining: 3m 44s
118:	learn: 0.0668109	test: 0.0846880	best: 0.0846751 (116)	total: 13.8s	remaining: 3m 44s
119:	learn: 0.0667689	test: 0.0846810	best: 0.0846751 (116)	total: 13.9s	remaining: 3m 43s
120:	learn: 0.0667342	test: 0.0846857	best: 0.0846751 (116)	total: 14s	remaining: 3m 43s
121:	learn: 0.0666478	test: 0.0846603	best: 0.0846603 (121)	total: 14.1s	remaining: 3m 43s
122:	learn: 0.0666190	test: 0.0846568	best: 0.0846568 (122)	total: 14.2s	remaining: 3m 42s
123:	learn: 0.0665691	test: 0.0846628	best: 0.0846568 (122)	total: 14.3s	remaining: 3m 42s
124:	learn: 0.0665055	test: 0.0846460	best: 0.0846460 (124)	total: 14.4s	remaining: 3m 42s
125:	learn: 0.0664736	test: 0.0846435	best: 0.0846435 (125)	total: 14.5s	remaining: 3m 41s
126:	learn: 0.0664402	test: 0.0846241	best: 0.0846241 (126)	total: 14.6s	remaining: 3m 41s
127:	learn: 0.0664146	test: 0.0846306	best: 0.0846241 (126)	total: 14.7s	remaining: 3m 40s
128:	learn: 0.0663460	test: 0.0846120	best: 0.0846120 (128)	total: 14.8s	remaining: 3m 40s
129:	learn: 0.0662951	test: 0.0846135	best: 0.0846120 (128)	total: 14.9s	remaining: 3m 40s
130:	learn: 0.0662153	test: 0.0845976	best: 0.0845976 (130)	total: 15.1s	remaining: 3m 40s
131:	learn: 0.0661883	test: 0.0845660	best: 0.0845660 (131)	total: 15.1s	remaining: 3m 39s
132:	learn: 0.0661491	test: 0.0845472	best: 0.0845472 (132)	total: 15.2s	remaining: 3m 39s
133:	learn: 0.0661371	test: 0.0845461	best: 0.0845461 (133)	total: 15.3s	remaining: 3m 38s
134:	learn: 0.0660525	test: 0.0844996	best: 0.0844996 (134)	total: 15.4s	remaining: 3m 38s
135:	learn: 0.0659960	test: 0.0844936	best: 0.0844936 (135)	total: 15.5s	remaining: 3m 38s
136:	learn: 0.0659458	test: 0.0845081	best: 0.0844936 (135)	total: 15.7s	remaining: 3m 38s
137:	learn: 0.0659240	test: 0.0845081	best: 0.0844936 (135)	total: 15.7s	remaining: 3m 37s
138:	learn: 0.0658246	test: 0.0845083	best: 0.0844936 (135)	total: 15.8s	remaining: 3m 37s
139:	learn: 0.0657688	test: 0.0845119	best: 0.0844936 (135)	total: 16s	remaining: 3m 37s
140:	learn: 0.0656729	test: 0.0844492	best: 0.0844492 (140)	total: 16.1s	remaining: 3m 37s
141:	learn: 0.0655893	test: 0.0844567	best: 0.0844492 (140)	total: 16.2s	remaining: 3m 37s
142:	learn: 0.0655379	test: 0.0844474	best: 0.0844474 (142)	total: 16.3s	remaining: 3m 37s
143:	learn: 0.0654965	test: 0.0844385	best: 0.0844385 (143)	total: 16.4s	remaining: 3m 36s
144:	learn: 0.0654477	test: 0.0844524	best: 0.0844385 (143)	total: 16.5s	remaining: 3m 36s
145:	learn: 0.0654324	test: 0.0844426	best: 0.0844385 (143)	total: 16.6s	remaining: 3m 36s
146:	learn: 0.0653777	test: 0.0844544	best: 0.0844385 (143)	total: 16.7s	remaining: 3m 35s
147:	learn: 0.0653077	test: 0.0844344	best: 0.0844344 (147)	total: 16.8s	remaining: 3m 35s
148:	learn: 0.0652885	test: 0.0844354	best: 0.0844344 (147)	total: 16.9s	remaining: 3m 35s
149:	learn: 0.0652609	test: 0.0844290	best: 0.0844290 (149)	total: 17s	remaining: 3m 34s
150:	learn: 0.0652409	test: 0.0844312	best: 0.0844290 (149)	total: 17.1s	remaining: 3m 34s
151:	learn: 0.0652216	test: 0.0844310	best: 0.0844290 (149)	total: 17.2s	remaining: 3m 34s
152:	learn: 0.0651608	test: 0.0844199	best: 0.0844199 (152)	total: 17.3s	remaining: 3m 33s
153:	learn: 0.0651298	test: 0.0844266	best: 0.0844199 (152)	total: 17.4s	remaining: 3m 33s
154:	learn: 0.0650690	test: 0.0844117	best: 0.0844117 (154)	total: 17.5s	remaining: 3m 33s
155:	learn: 0.0650312	test: 0.0844301	best: 0.0844117 (154)	total: 17.6s	remaining: 3m 33s
156:	learn: 0.0649936	test: 0.0844173	best: 0.0844117 (154)	total: 17.8s	remaining: 3m 34s
157:	learn: 0.0649740	test: 0.0844215	best: 0.0844117 (154)	total: 17.9s	remaining: 3m 34s
158:	learn: 0.0649587	test: 0.0844246	best: 0.0844117 (154)	total: 18s	remaining: 3m 34s
159:	learn: 0.0649441	test: 0.0844317	best: 0.0844117 (154)	total: 18.2s	remaining: 3m 34s
160:	learn: 0.0649272	test: 0.0844283	best: 0.0844117 (154)	total: 18.3s	remaining: 3m 34s
161:	learn: 0.0649109	test: 0.0844281	best: 0.0844117 (154)	total: 18.4s	remaining: 3m 33s
162:	learn: 0.0648626	test: 0.0844289	best: 0.0844117 (154)	total: 18.5s	remaining: 3m 33s
163:	learn: 0.0648444	test: 0.0844257	best: 0.0844117 (154)	total: 18.6s	remaining: 3m 33s
164:	learn: 0.0648061	test: 0.0844107	best: 0.0844107 (164)	total: 18.7s	remaining: 3m 33s
165:	learn: 0.0647842	test: 0.0844118	best: 0.0844107 (164)	total: 18.8s	remaining: 3m 33s
166:	learn: 0.0647550	test: 0.0843905	best: 0.0843905 (166)	total: 18.9s	remaining: 3m 32s
167:	learn: 0.0647415	test: 0.0843849	best: 0.0843849 (167)	total: 19s	remaining: 3m 32s
168:	learn: 0.0646863	test: 0.0843640	best: 0.0843640 (168)	total: 19.1s	remaining: 3m 32s
169:	learn: 0.0646758	test: 0.0843639	best: 0.0843639 (169)	total: 19.2s	remaining: 3m 32s
170:	learn: 0.0646449	test: 0.0843688	best: 0.0843639 (169)	total: 19.3s	remaining: 3m 32s
171:	learn: 0.0646287	test: 0.0843593	best: 0.0843593 (171)	total: 19.4s	remaining: 3m 31s
172:	learn: 0.0645869	test: 0.0843550	best: 0.0843550 (172)	total: 19.6s	remaining: 3m 32s
173:	learn: 0.0645680	test: 0.0843539	best: 0.0843539 (173)	total: 19.7s	remaining: 3m 32s
174:	learn: 0.0644838	test: 0.0843415	best: 0.0843415 (174)	total: 19.9s	remaining: 3m 32s
175:	learn: 0.0644621	test: 0.0843277	best: 0.0843277 (175)	total: 20s	remaining: 3m 32s
176:	learn: 0.0644028	test: 0.0843130	best: 0.0843130 (176)	total: 20.1s	remaining: 3m 32s
177:	learn: 0.0643499	test: 0.0842997	best: 0.0842997 (177)	total: 20.3s	remaining: 3m 32s
178:	learn: 0.0643022	test: 0.0842927	best: 0.0842927 (178)	total: 20.4s	remaining: 3m 33s
179:	learn: 0.0642739	test: 0.0842973	best: 0.0842927 (178)	total: 20.6s	remaining: 3m 33s
180:	learn: 0.0642641	test: 0.0842969	best: 0.0842927 (178)	total: 20.7s	remaining: 3m 33s
181:	learn: 0.0642170	test: 0.0842917	best: 0.0842917 (181)	total: 20.9s	remaining: 3m 33s
182:	learn: 0.0641936	test: 0.0842817	best: 0.0842817 (182)	total: 21s	remaining: 3m 34s
183:	learn: 0.0641806	test: 0.0842770	best: 0.0842770 (183)	total: 21.1s	remaining: 3m 34s
184:	learn: 0.0641013	test: 0.0842845	best: 0.0842770 (183)	total: 21.3s	remaining: 3m 34s
185:	learn: 0.0640240	test: 0.0842369	best: 0.0842369 (185)	total: 21.5s	remaining: 3m 34s
186:	learn: 0.0640111	test: 0.0842359	best: 0.0842359 (186)	total: 21.6s	remaining: 3m 35s
187:	learn: 0.0640000	test: 0.0842323	best: 0.0842323 (187)	total: 21.7s	remaining: 3m 35s
188:	learn: 0.0639747	test: 0.0842224	best: 0.0842224 (188)	total: 21.9s	remaining: 3m 35s
189:	learn: 0.0639634	test: 0.0842143	best: 0.0842143 (189)	total: 22s	remaining: 3m 35s
190:	learn: 0.0639256	test: 0.0842067	best: 0.0842067 (190)	total: 22.1s	remaining: 3m 34s
191:	learn: 0.0638962	test: 0.0842042	best: 0.0842042 (191)	total: 22.2s	remaining: 3m 34s
192:	learn: 0.0638279	test: 0.0842082	best: 0.0842042 (191)	total: 22.3s	remaining: 3m 34s
193:	learn: 0.0638131	test: 0.0842121	best: 0.0842042 (191)	total: 22.4s	remaining: 3m 33s
194:	learn: 0.0637756	test: 0.0842157	best: 0.0842042 (191)	total: 22.5s	remaining: 3m 33s
195:	learn: 0.0637521	test: 0.0842145	best: 0.0842042 (191)	total: 22.6s	remaining: 3m 33s
196:	learn: 0.0637302	test: 0.0842151	best: 0.0842042 (191)	total: 22.7s	remaining: 3m 32s
197:	learn: 0.0637206	test: 0.0842066	best: 0.0842042 (191)	total: 22.7s	remaining: 3m 32s
198:	learn: 0.0637027	test: 0.0842057	best: 0.0842042 (191)	total: 22.8s	remaining: 3m 32s
199:	learn: 0.0636287	test: 0.0842007	best: 0.0842007 (199)	total: 23s	remaining: 3m 32s
200:	learn: 0.0635893	test: 0.0841920	best: 0.0841920 (200)	total: 23.1s	remaining: 3m 31s
201:	learn: 0.0635410	test: 0.0841821	best: 0.0841821 (201)	total: 23.2s	remaining: 3m 31s
202:	learn: 0.0635128	test: 0.0841830	best: 0.0841821 (201)	total: 23.3s	remaining: 3m 31s
203:	learn: 0.0634933	test: 0.0841707	best: 0.0841707 (203)	total: 23.4s	remaining: 3m 31s
204:	learn: 0.0634690	test: 0.0841534	best: 0.0841534 (204)	total: 23.5s	remaining: 3m 30s
205:	learn: 0.0634540	test: 0.0841496	best: 0.0841496 (205)	total: 23.6s	remaining: 3m 30s
206:	learn: 0.0634150	test: 0.0841235	best: 0.0841235 (206)	total: 23.6s	remaining: 3m 30s
207:	learn: 0.0633548	test: 0.0841070	best: 0.0841070 (207)	total: 23.8s	remaining: 3m 30s
208:	learn: 0.0633156	test: 0.0841017	best: 0.0841017 (208)	total: 23.8s	remaining: 3m 29s
209:	learn: 0.0632916	test: 0.0840844	best: 0.0840844 (209)	total: 23.9s	remaining: 3m 29s
210:	learn: 0.0632679	test: 0.0840856	best: 0.0840844 (209)	total: 24s	remaining: 3m 29s
211:	learn: 0.0631763	test: 0.0840817	best: 0.0840817 (211)	total: 24.1s	remaining: 3m 29s
212:	learn: 0.0631132	test: 0.0840495	best: 0.0840495 (212)	total: 24.2s	remaining: 3m 28s
213:	learn: 0.0630970	test: 0.0840454	best: 0.0840454 (213)	total: 24.3s	remaining: 3m 28s
214:	learn: 0.0630674	test: 0.0840224	best: 0.0840224 (214)	total: 24.4s	remaining: 3m 28s
215:	learn: 0.0629896	test: 0.0839860	best: 0.0839860 (215)	total: 24.5s	remaining: 3m 27s
216:	learn: 0.0629452	test: 0.0839592	best: 0.0839592 (216)	total: 24.6s	remaining: 3m 27s
217:	learn: 0.0629253	test: 0.0839551	best: 0.0839551 (217)	total: 24.7s	remaining: 3m 27s
218:	learn: 0.0628501	test: 0.0839512	best: 0.0839512 (218)	total: 24.8s	remaining: 3m 27s
219:	learn: 0.0628346	test: 0.0839395	best: 0.0839395 (219)	total: 24.9s	remaining: 3m 26s
220:	learn: 0.0627762	test: 0.0839326	best: 0.0839326 (220)	total: 25s	remaining: 3m 26s
221:	learn: 0.0627222	test: 0.0839226	best: 0.0839226 (221)	total: 25.1s	remaining: 3m 26s

       train     val    test
loss 0.03487 0.08084 0.07215
r2   0.81625 0.25463 0.21736

In [ ]:
meta_params = {'timestamp': dt.now().strftime('%Y-%m-%d %H:%M:%S'),
    'embeddings': model_name, 'db_name': db_name}
meta_params.update(params)
meta_params['best_iteration'] = model.best_iteration_

meta_params['train_loss'] = model.best_score_['learn'][params['loss_function']]
meta_params['val_loss'] = model.best_score_['validation'][params['loss_function']]
meta_params['test_loss'] = model.eval_metrics(test_pool, ['RMSE'])['RMSE'][-1]

meta_params['train_r2'] = model.score(train_embeddings, y_train)
meta_params['val_r2'] = model.score(val_embeddings, y_val)
meta_params['test_r2'] = model.score(test_embeddings, y_test)

end = time.time()
meta_params['time'] = end - start

run_results_file = 'run_results.csv'
run_results_df = (pd.read_csv('run_results.csv')
                  if os.path.exists(run_results_file)
                  else pd.DataFrame(columns=meta_params.keys()))
run_results_df.loc[len(run_results_df)] = meta_params
run_results_df.to_csv(run_results_file, index=False)
run_results_df = pd.read_csv(run_results_file)

# print 3 digits
pd.options.display.float_format = '{:.5f}'.format

print('Past Results')
print(run_results_df.sort_values(by='test_loss').head(16))
print()
print('This Run')
print(run_results_df.tail(1))

In [ ]:
rm iter_captioned_minilm_run_results.csv

In [ ]:
# Fit model

%%time

import pandas as pd

run_results_file = 'iter_captioned_minilm_run_results.csv'

pd.set_option('display.width', 1000)

from datetime import datetime as dt
from catboost import CatBoostRegressor, Pool
import time

from tqdm.notebook import tqdm
tqdm.pandas()

from scipy import stats

y_train = train_df['video_view_count'].to_numpy()
y_val = val_df['video_view_count'].to_numpy()
y_test = test_df['video_view_count'].to_numpy()
y_my = my_df['video_view_count'].to_numpy()

train_pool = Pool(train_embeddings, y_train)
val_pool = Pool(val_embeddings, y_val)
test_pool = Pool(test_embeddings, y_test)
my_pool = Pool(my_embeddings, y_my)

iterations = [1024]

pbar = tqdm(total=sum(iterations))

for iteration in iterations:

  start = time.time()


  params = {
      'iterations': iteration,
      'depth': 8,
      'learning_rate': .05,
      'l2_leaf_reg': 100,
      'random_strength': 10,
  }

  print(params)

  model = CatBoostRegressor(**params,
                            random_seed=42,
                            verbose=True,
                            task_type='GPU',
                            loss_function='RMSE',
                            eval_metric='R2',
                            metric_period=64,
                            )
  model.fit(train_pool, eval_set=val_pool, verbose=True)

  loss_data = {
      'train': model.eval_metrics(train_pool, ['RMSE'])['RMSE'][-1],
      'val': model.eval_metrics(val_pool, ['RMSE'])['RMSE'][-1],
      'test': model.eval_metrics(test_pool, ['RMSE'])['RMSE'][-1]
  }
  r2_data = {
      'train': model.score(train_embeddings, y_train),
      'val': model.score(val_embeddings, y_val),
      'test': model.score(test_embeddings, y_test)
  }
  p_data = {
      'train': 0,
      'val': val_p,
      'test': test_p
  }

  loss_series = pd.Series(loss_data, name='loss')
  r2_series = pd.Series(r2_data, name='r2')
  p_series = pd.Series(p_data, name='p')
  metrics_df = pd.concat([loss_series, r2_series, p_series], axis=1)
  print(metrics_df.T)
  print()

  y_pred_train = model.predict(train_pool)
  y_pred_val = model.predict(val_pool)
  y_pred_test = model.predict(test_pool)

  train_residuals = y_train - y_pred_train
  val_residuals = y_val - y_pred_val
  test_residuals = y_test - y_pred_test

  val_t, val_p = stats.mannwhitneyu(train_residuals, val_residuals)
  test_t, test_p = stats.mannwhitneyu(train_residuals, test_residuals)

  params['best_iteration'] = model.best_iteration_

  params['train_loss'] = model.best_score_['learn']['RMSE']
  params['val_loss'] = model.best_score_['validation']['RMSE']
  params['val_p'] = val_p

  params['train_r2'] = model.score(train_embeddings, y_train)
  params['val_r2'] = model.score(val_embeddings, y_val)
  params['test_r2'] = model.score(test_embeddings, y_test)

  params['time'] = time.time() - start

  run_results_df = (pd.read_csv(run_results_file)
                    if os.path.exists(run_results_file)
                    else pd.DataFrame(columns=params.keys()))

  run_results_df.loc[len(run_results_df)] = params
  run_results_df.to_csv(run_results_file, index=False)

  pbar.update(iteration)

pbar.close()

run_results_df = pd.read_csv(run_results_file)

# print 3 digits
pd.options.display.float_format = '{:.5f}'.format

remap = {
    'iterations': 'iter',
    'learning_rate': 'lr',
    'loss_function': 'loss',
    'l2_leaf_reg': 'l2',
    'best_iteration': 'top_iter',
}

run_results_df.rename(columns=remap, inplace=True)

pd.set_option('display.max_rows', None)

print('Past Results')
print(run_results_df)
print()

  0%|          | 0/1024 [00:00<?, ?it/s]

{'iterations': 1024, 'depth': 8, 'learning_rate': 0.05, 'l2_leaf_reg': 100, 'random_strength': 10}

Metric R2 is not implemented on GPU. Will use CPU for metric computation, this could significantly affect learning time

0:	learn: 0.0055661	test: 0.0029995	best: 0.0029995 (0)	total: 197ms	remaining: 3m 21s
64:	learn: 0.1746802	test: 0.1243122	best: 0.1243122 (64)	total: 6.61s	remaining: 1m 37s
128:	learn: 0.2294795	test: 0.1531207	best: 0.1531207 (128)	total: 14.4s	remaining: 1m 39s
192:	learn: 0.2647828	test: 0.1676837	best: 0.1676837 (192)	total: 20.8s	remaining: 1m 29s
256:	learn: 0.2987036	test: 0.1776739	best: 0.1776739 (256)	total: 28s	remaining: 1m 23s
320:	learn: 0.3300412	test: 0.1850144	best: 0.1850144 (320)	total: 34.4s	remaining: 1m 15s
384:	learn: 0.3544407	test: 0.1922712	best: 0.1922712 (384)	total: 41.1s	remaining: 1m 8s
448:	learn: 0.3793719	test: 0.1978704	best: 0.1978704 (448)	total: 47.3s	remaining: 1m
512:	learn: 0.3987404	test: 0.2015775	best: 0.2015775 (512)	total: 53.1s	remaining: 52.9s
576:	learn: 0.4172180	test: 0.2044605	best: 0.2044605 (576)	total: 1m	remaining: 46.5s
640:	learn: 0.4334769	test: 0.2082419	best: 0.2082419 (640)	total: 1m 5s	remaining: 39.3s
704:	learn: 0.4494328	test: 0.2104328	best: 0.2104328 (704)	total: 1m 12s	remaining: 32.8s
768:	learn: 0.4639789	test: 0.2130350	best: 0.2130350 (768)	total: 1m 18s	remaining: 26s
832:	learn: 0.4771618	test: 0.2153472	best: 0.2153472 (832)	total: 1m 24s	remaining: 19.3s
896:	learn: 0.4889676	test: 0.2169090	best: 0.2169090 (896)	total: 1m 30s	remaining: 12.9s
960:	learn: 0.5021126	test: 0.2192387	best: 0.2192387 (960)	total: 1m 36s	remaining: 6.33s
1023:	learn: 0.5137329	test: 0.2211462	best: 0.2211462 (1023)	total: 1m 43s	remaining: 0us
bestTest = 0.2211462
bestIteration = 1023
       train     val    test
loss 0.05673 0.08264 0.07301
r2   0.51373 0.22115 0.19868
p    0.00000 0.00007 0.00000

Past Results
    iter  depth      lr         l2  random_strength  top_iter  train_loss  val_loss   val_p  train_r2  val_r2  test_r2      time
0   1024      2 0.10000    0.00000          0.00000       960     0.05470   0.08458 0.01528   0.53652 0.18423  0.16592  14.11039
1   1024      2 0.10000    1.00000          0.00000       960     0.05559   0.08436 0.02478   0.52414 0.18830  0.15356  12.02985
2   1024      2 0.10000    1.00000          0.10000      1023     0.05577   0.08453 0.00569   0.53002 0.18505  0.14605  16.78681
3   2048      2 0.10000    0.00000          0.00000      1984     0.04719   0.08438 0.00022   0.65863 0.18809  0.14784  24.99347
4   2048      2 0.05000    0.00000          0.00000      1792     0.05446   0.08423 0.00626   0.52661 0.19093  0.15299  26.52646
5   2048      2 0.02500    0.00000          0.00000      2047     0.06126   0.08465 0.06116   0.43302 0.18274  0.15344  26.14149
6   4096      2 0.02500    0.00000          0.00000      3904     0.05434   0.08409 0.00364   0.54552 0.19366  0.15106  52.46462
7   4096      2 0.01250    0.00000          0.00000      4095     0.06135   0.08456 0.08599   0.43139 0.18456  0.15671  53.78760
8   1024      8 0.10000    0.00000          0.00000       832     0.02077   0.08269 0.00000   0.92316 0.22020  0.16229  90.30811
9   1024      8 0.10000  100.00000          0.00000      1023     0.04647   0.08156 0.00000   0.67372 0.24131  0.21977 104.94056
10  1024      8 0.10000 1000.00000          0.00000      1023     0.05875   0.08306 0.00004   0.47861 0.21318  0.20391 129.13341
11  1024      8 0.10000        NaN          1.00000      1023     0.02640   0.08212 0.00000   0.89468 0.23089  0.18750  95.28640
12  1024      8 0.10000  100.00000          1.00000      1023     0.04659   0.08174 0.00000   0.67201 0.23798  0.20534 106.99927
13  1024      8 0.10000 1000.00000          1.00000      1023     0.05873   0.08316 0.00007   0.47886 0.21137  0.20066 129.49456
14  1024      8 0.05000  100.00000         10.00000      1023     0.05673   0.08264 0.00192   0.51373 0.22115  0.19868 106.59049

CPU times: user 1min 42s, sys: 8.21 s, total: 1min 50s
Wall time: 1min 46s

In [ ]:
      # dont use scientific notation
pd.options.display.float_format = '{:.3f}'.format
# find model with '33' in name
file_names = os.listdir('/data/models')
file_names = [f for f in file_names if '33' in f]
file_name = file_names[0]
model = model.load_model(f'/data/models/{file_name}')

# model = model.load_model(f'/data/models/{model_name}_{db_name}_model.cbm')
temp_my_df = my_df.copy()
temp_my_df['predicted_views'] = model.predict(my_pool)
print(model.score(my_pool))
temp_my_df = temp_my_df[['video_title', 'video_view_count', 'predicted_views']]
temp_my_df.sort_values(by='predicted_views', ascending=False)

FileNotFoundError: [Errno 2] No such file or directory: '/data/models'

In [ ]:
# save model
model.save_model(f'models/{model_name}_{db_name}_model_31\.cbm')