In [1]:
import pandas as pd
import sqlalchemy

# Create a connection to the database
engine = sqlalchemy.create_engine('sqlite:///../data/video_data.db')

channel_statistics_df = pd.read_sql('SELECT * FROM channel_statistics', engine)
channel_uploads_df = pd.read_sql('SELECT * FROM channel_uploads', engine)
videos_df = pd.read_sql('SELECT * FROM videos', engine)
search_results_df = pd.read_sql('SELECT * FROM search_results', engine)

OperationalError: (sqlite3.OperationalError) no such table: channel_uploads
[SQL: SELECT * FROM channel_uploads]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [3]:
channel_uploads_df

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,...,snippet.position,snippet.resourceId.kind,snippet.resourceId.videoId,snippet.videoOwnerChannelTitle,snippet.videoOwnerChannelId,contentDetails.videoId,contentDetails.videoPublishedAt,snippet.thumbnails.maxres.url,snippet.thumbnails.maxres.width,snippet.thumbnails.maxres.height
0,youtube#playlistItem,mV-xHcEszMOado0uNgyD30D8Yhs,VVVpc3Z5Nm0tVEJlNEEtUmhOMWpYUk5nLlNLSWtuQ0FkYnFB,2022-05-10T20:21:03Z,UCisvy6m-TBe4A-RhN1jXRNg,for the fans of drifting and hardstyle music,"Japanese street drifting, professional driftin...",https://i.ytimg.com/vi/SKIknCAdbqA/default.jpg,120,90,...,0,youtube#video,SKIknCAdbqA,Murphy Boi,UCisvy6m-TBe4A-RhN1jXRNg,SKIknCAdbqA,2022-05-10T20:21:03Z,None,NaN,NaN
1,youtube#playlistItem,G5CUntYkScK7Nti_l5Fyd7gLSJg,VVVpc3Z5Nm0tVEJlNEEtUmhOMWpYUk5nLkUwVzYzejg1X3kw,2022-04-28T11:53:00Z,UCisvy6m-TBe4A-RhN1jXRNg,Hardstyle Meets JDM,Best Forza Horizon 5 music video you've seen w...,https://i.ytimg.com/vi/E0W63z85_y0/default.jpg,120,90,...,1,youtube#video,E0W63z85_y0,Murphy Boi,UCisvy6m-TBe4A-RhN1jXRNg,E0W63z85_y0,2022-04-28T11:53:00Z,https://i.ytimg.com/vi/E0W63z85_y0/maxresdefau...,1280.0,720.0
2,youtube#playlistItem,g4tD7iIkNib5lgkRYfuw-uNHR2c,VVVpc3Z5Nm0tVEJlNEEtUmhOMWpYUk5nLjM0QldfLXFiRm1v,2022-03-01T08:49:17Z,UCisvy6m-TBe4A-RhN1jXRNg,"How To Save a Life - Need for Speed (2014), Pe...",Movie music video Need for Speed (2014)\n-\n-\...,https://i.ytimg.com/vi/34BW_-qbFmo/default.jpg,120,90,...,2,youtube#video,34BW_-qbFmo,Murphy Boi,UCisvy6m-TBe4A-RhN1jXRNg,34BW_-qbFmo,2022-03-01T08:49:17Z,https://i.ytimg.com/vi/34BW_-qbFmo/maxresdefau...,1280.0,720.0
3,youtube#playlistItem,_LGaB11x7cDklNe52D4XmBo9fgw,VVVpc3Z5Nm0tVEJlNEEtUmhOMWpYUk5nLmswRy01NUY1eHk4,2022-01-22T13:02:22Z,UCisvy6m-TBe4A-RhN1jXRNg,German Cars In Mexico,"Classic BMW, Audi and Mercedes-Benz cars drift...",https://i.ytimg.com/vi/k0G-55F5xy8/default.jpg,120,90,...,3,youtube#video,k0G-55F5xy8,Murphy Boi,UCisvy6m-TBe4A-RhN1jXRNg,k0G-55F5xy8,2022-01-22T13:02:22Z,https://i.ytimg.com/vi/k0G-55F5xy8/maxresdefau...,1280.0,720.0
4,youtube#playlistItem,caNrvYJuGb9iXC-WyrQbtgaSfBA,VVVpc3Z5Nm0tVEJlNEEtUmhOMWpYUk5nLkJOalRabEV3WFRz,2021-12-14T18:53:33Z,UCisvy6m-TBe4A-RhN1jXRNg,Russ - Pull The Trigger x Car Music Video,Videos stolen from LIMMA Group:\n\nhttps://you...,https://i.ytimg.com/vi/BNjTZlEwXTs/default.jpg,120,90,...,4,youtube#video,BNjTZlEwXTs,Murphy Boi,UCisvy6m-TBe4A-RhN1jXRNg,BNjTZlEwXTs,2021-12-14T18:53:33Z,https://i.ytimg.com/vi/BNjTZlEwXTs/maxresdefau...,1280.0,720.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12059,youtube#playlistItem,ih_8qkUDX5FAt0PBpG14c__HW4k,VVU0WnZtVWNEUEVVSGt4cmlBczRPajd3LnRhLVk3SDJENGtV,2020-07-05T14:37:07Z,UC4ZvmUcDPEUHkxriAs4Oj7w,how to download adobe reader,,https://i.ytimg.com/vi/ta-Y7H2D4kU/default.jpg,120,90,...,62,youtube#video,ta-Y7H2D4kU,LxGT GamingZ,UC4ZvmUcDPEUHkxriAs4Oj7w,ta-Y7H2D4kU,2020-07-05T14:37:07Z,https://i.ytimg.com/vi/ta-Y7H2D4kU/maxresdefau...,1280.0,720.0
12060,youtube#playlistItem,NL24vmxZ9hCdSR-ztbQG81Qy9dQ,VVU0WnZtVWNEUEVVSGt4cmlBczRPajd3LnpTSzJkcGNxc3VJ,2020-07-05T14:25:24Z,UC4ZvmUcDPEUHkxriAs4Oj7w,how to download driver max,,https://i.ytimg.com/vi/zSK2dpcqsuI/default.jpg,120,90,...,63,youtube#video,zSK2dpcqsuI,LxGT GamingZ,UC4ZvmUcDPEUHkxriAs4Oj7w,zSK2dpcqsuI,2020-07-05T14:25:24Z,https://i.ytimg.com/vi/zSK2dpcqsuI/maxresdefau...,1280.0,720.0
12061,youtube#playlistItem,uUOuxRfFs3AFzNp37mZDvXiihaQ,VVU0WnZtVWNEUEVVSGt4cmlBczRPajd3LjBtQ280SU80N25r,2020-07-05T03:28:51Z,UC4ZvmUcDPEUHkxriAs4Oj7w,how to download tekken 3 on pc,,https://i.ytimg.com/vi/0mCo4IO47nk/default.jpg,120,90,...,64,youtube#video,0mCo4IO47nk,LxGT GamingZ,UC4ZvmUcDPEUHkxriAs4Oj7w,0mCo4IO47nk,2020-07-05T03:28:51Z,https://i.ytimg.com/vi/0mCo4IO47nk/maxresdefau...,1280.0,720.0
12062,youtube#playlistItem,bVmYxzB2Tif9uKdZsVzvqIrgQd4,VVU0WnZtVWNEUEVVSGt4cmlBczRPajd3Ljg1ZExsWUZZSnBr,2020-07-04T13:12:55Z,UC4ZvmUcDPEUHkxriAs4Oj7w,how to download gta san andreas remastered mod,,https://i.ytimg.com/vi/85dLlYFYJpk/default.jpg,120,90,...,65,youtube#video,85dLlYFYJpk,LxGT GamingZ,UC4ZvmUcDPEUHkxriAs4Oj7w,85dLlYFYJpk,2020-07-04T13:12:55Z,https://i.ytimg.com/vi/85dLlYFYJpk/maxresdefau...,1280.0,720.0
12063,youtube#playlistItem,g9qRAXreH0JYZ2BkJbx-a2qr4Lk,VVU0WnZtVWNEUEVVSGt4cmlBczRPajd3Lmd3MWQtdUpPMXVn,2020-07-04T09:32:13Z,UC4ZvmUcDPEUHkxriAs4Oj7w,how to download uttorent,,https://i.ytimg.com/vi/gw1d-uJO1ug/default.jpg,120,90,...,66,youtube#video,gw1d-uJO1ug,LxGT GamingZ,UC4ZvmUcDPEUHkxriAs4Oj7w,gw1d-uJO1ug,2020-07-04T09:32:13Z,https://i.ytimg.com/vi/gw1d-uJO1ug/maxresdefau...,1280.0,720.0

In [14]:
channel_statistics = %sql SELECT * FROM channel_statistics;
channel_statistics_df = channel_statistics.DataFrame()
channel_statistics_df

,kind,etag,id,snippet.title,snippet.description,snippet.customUrl,snippet.publishedAt,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,...,contentDetails.relatedPlaylists.uploads,statistics.viewCount,statistics.subscriberCount,statistics.hiddenSubscriberCount,statistics.videoCount,topicDetails.topicIds,topicDetails.topicCategories,snippet.country,snippet.defaultLanguage,queryTimestamp
0,youtube#channel,ioq1AyzAUoR7oYsYPXKH6cgKUqo,UCcvF79bG3jBlRNl-hAeiZrw,Zuldim,Making videos about the things I love.\n\n@Zul...,@zuldimyt,2016-02-08T01:35:52Z,https://yt3.ggpht.com/fg1nj43_QqhA_gYnm7nJu1yU...,88,88,...,UUcvF79bG3jBlRNl-hAeiZrw,2816123,20500,0,103,"/m/02ntfj,/m/025zzc,/m/0403l3g,/m/0bzvm2",https://en.wikipedia.org/wiki/Action-adventure...,None,None,2024-08-01 13:07:59.923188
1,youtube#channel,257DlTn1jhOnRT5DmP01ars0NmE,UC_BGCLKgUOyO5pirBbXojWQ,footprints of love,"In this channel, we are going to tell the stor...",@user-mi3nr3eg6n,2024-05-18T20:56:49.841842Z,https://yt3.ggpht.com/hTLOsAVSlHXWYZLhjEHHVIUq...,88,88,...,UU_BGCLKgUOyO5pirBbXojWQ,2735458,9550,0,74,/m/019_rr,https://en.wikipedia.org/wiki/Lifestyle_(socio...,GB,None,2024-08-01 13:07:59.923188
2,youtube#channel,-IGDCSW0EFiVBtoNjq_YbLY0vgs,UCWyMs0f2x3VaXFx5OYaBfaQ,Peeren1,Peeren is the story of a Nomadic & Rural famil...,@peeren12023,2023-12-29T23:24:56.898384Z,https://yt3.ggpht.com/1psN3EqRgxBUXRPx3HwJ1M4K...,88,88,...,UUWyMs0f2x3VaXFx5OYaBfaQ,5225096,16200,0,199,"/m/02vxn,/m/019_rr,/m/02jjt","https://en.wikipedia.org/wiki/Film,https://en....",TR,None,2024-08-01 13:07:59.923188
3,youtube#channel,1Ezb1B5E4tKK4xBc7zdovwJeFpc,UCRf7LpR7yeDN2uC90aVduyw,Saviour 3.0,My Name Is Josiah Doggett! Producer and Video ...,@saviour30,2017-10-11T22:44:00Z,https://yt3.ggpht.com/iPK6LrVISlDJj0PbWOuOr4ds...,88,88,...,UURf7LpR7yeDN2uC90aVduyw,1594182,10400,0,655,"/m/0403l3g,/m/025zzc,/m/0bzvm2,/m/02ntfj",https://en.wikipedia.org/wiki/Role-playing_vid...,GB,None,2024-08-01 13:07:59.923188
4,youtube#channel,ptEtwSB153t_HOFsKalnylD18Vg,UCboTk1F9UrX5GLu33vFa4sw,TOPDARK.COM,TOPDARK.COM es el lugar ideal para encontrar t...,@topdarkcom,2014-01-03T08:16:22Z,https://yt3.ggpht.com/3yj1VhdPhMCh_R4u3drp_5hD...,88,88,...,UUboTk1F9UrX5GLu33vFa4sw,85545890,762000,0,204,"/g/120yrv6h,/m/01k8wb,/m/019_rr","https://en.wikipedia.org/wiki/Tourism,https://...",PE,es-419,2024-08-01 13:07:59.923188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10154,youtube#channel,Pl5t4gTrNeF8BRFZJVvefvPSvO8,UCUG5BEHfTZXPLwSHl4NSy3Q,Amazon Seller University,"Education to help brands, businesses, and entr...",@amazonselleruniversity,2016-10-27T22:47:58Z,https://yt3.ggpht.com/7SGkuJV_VZ1k-blLQc99dIPy...,88,88,...,UUUG5BEHfTZXPLwSHl4NSy3Q,11773019,207000,0,889,"/m/01k8wb,/m/07c1v,/m/019_rr,/g/120y8l81","https://en.wikipedia.org/wiki/Knowledge,https:...",US,None,2024-08-08 00:49:57.654221
10155,youtube#channel,QabIa8k3h3hdAl_6hWJKLbxPC1A,UCjebymTpAoBTuecsf-AtNWQ,Король Твого Міста,"Український подкаст, в якому кожен випуск прис...",@koroltvogomista,2022-08-11T10:12:05.403501Z,https://yt3.ggpht.com/2EFfYeA6kj4iZ5hsGmUS0oo7...,88,88,...,UUjebymTpAoBTuecsf-AtNWQ,2044440,87500,0,78,"/m/09kqc,/m/02jjt,/m/098wr","https://en.wikipedia.org/wiki/Humour,https://e...",UA,None,2024-08-08 00:49:57.654221
10156,youtube#channel,AyulOCfJwNFMN0R4EqiXb44X7-U,UCRO5m0LkVuLaeKDsp-AlnvQ,PReMA Event,,@premaevent2674,2020-07-20T13:50:07.238318Z,https://yt3.ggpht.com/ytc/AIdro_k5udRIdcqFh-5u...,88,88,...,UURO5m0LkVuLaeKDsp-AlnvQ,2177,36,0,33,"/m/098wr,/m/019_rr,/m/01k8wb,/m/0kt51","https://en.wikipedia.org/wiki/Society,https://...",TH,None,2024-08-08 00:49:57.654221
10157,youtube#channel,PdWgYfUDImd_H1NDxYgXPMyYtM4,UCd_OFhc2DSo_uvE2Xc3cPrA,Triple D,This is what happens when 3 noobs get together...,@tripled4250,2020-06-28T18:11:49.780651Z,https://yt3.ggpht.com/ytc/AIdro_k9nalJ5N6jjYtq...,88,88,...,UUd_OFhc2DSo_uvE2Xc3cPrA,1861,43,0,27,"/m/02ntfj,/m/0403l3g,/m/0bzvm2,/m/025zzc",https://en.wikipedia.org/wiki/Action-adventure...,ZA,en,2024-08-08 00:49:57.654221
10158,youtube#channel,JOvOnaehQhk26IexpLnEo16_4qM,UCShNA5j5wdsqm28FSfJJD1A,Cloud Native Rejekts,,@cloudnativerejekts,2019-05-31T09:45:52Z,https://yt3.ggpht.com/ytc/AIdro_nxfLxE95WrsMDw...,88,88,...,UUShNA5j5wdsqm28FSfJJD1A,72231,1260,0,290,"/m/07c1v,/m/01k8wb,/m/019_rr","https://en.wikipedia.org/wiki/Technology,https...",DE,None,2024-08-08 00:49:57.654221

In [15]:
video_statistics = %sql SELECT * FROM video_statistics;
video_statistics_df = video_statistics.DataFrame()
video_statistics_df

Empty DataFrame
Columns: [kind, etag, id, snippet_publishedAt, snippet_channelId, snippet_title, snippet_description, snippet_thumbnails_default_url, snippet_thumbnails_default_width, snippet_thumbnails_default_height, snippet_thumbnails_medium_url, snippet_thumbnails_medium_width, snippet_thumbnails_medium_height, snippet_thumbnails_high_url, snippet_thumbnails_high_width, snippet_thumbnails_high_height, snippet_thumbnails_standard_url, snippet_thumbnails_standard_width, snippet_thumbnails_standard_height, snippet_thumbnails_maxres_url, snippet_thumbnails_maxres_width, snippet_thumbnails_maxres_height, snippet_channelTitle, snippet_tags, snippet_categoryId, snippet_liveBroadcastContent, snippet_localized_title, snippet_localized_description, snippet_defaultAudioLanguage, contentDetails_duration, contentDetails_dimension, contentDetails_definition, contentDetails_caption, contentDetails_licensedContent, contentDetails_projection, statistics_viewCount, statistics_likeCount, statistics_favoriteCount, statistics_commentCount, topicDetails_topicCategories, contentDetails_contentRating_ytRating, contentDetails_regionRestriction_blocked, timestamp]
Index: []

[0 rows x 43 columns]

In [16]:
channel_uploads = %sql SELECT * FROM channel_uploads;
channel_uploads_df = channel_uploads.DataFrame()
channel_uploads_df

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,...,snippet.videoOwnerChannelTitle,snippet.videoOwnerChannelId,contentDetails.videoId,contentDetails.videoPublishedAt,snippet.thumbnails.standard.url,snippet.thumbnails.standard.width,snippet.thumbnails.standard.height,snippet.thumbnails.maxres.url,snippet.thumbnails.maxres.width,snippet.thumbnails.maxres.height
0,youtube#playlistItem,jqXGGuIA6Ji2Ze4ZR9GNLPxKZmc,VVVDUGpfc0xCWDhYRkEwSHVhNGtXVkFnLnM2Y29vQldQYUxV,2024-07-28T02:45:02Z,UCCPj_sLBX8XFA0Hua4kWVAg,Раскрытие секретов CONTROL - Финал,Раскрытие темных секретов CONTROL. Это прохожд...,https://i.ytimg.com/vi/s6cooBWPaLU/default.jpg,120,90,...,G. Dynasty Family Games,UCCPj_sLBX8XFA0Hua4kWVAg,s6cooBWPaLU,2024-07-28T02:45:02Z,None,NaN,NaN,None,NaN,NaN
1,youtube#playlistItem,dIJ3Lo_ck3Z85BDs8QUbFp4UDVU,VVVDUGpfc0xCWDhYRkEwSHVhNGtXVkFnLjdRa3k4MmFGVGc4,2024-07-21T02:00:05Z,UCCPj_sLBX8XFA0Hua4kWVAg,Увлекательная Deep Sky Derelicts ! Карты и ант...,Deep Sky Derelicts - это оригинальное сочетани...,https://i.ytimg.com/vi/7Qky82aFTg8/default.jpg,120,90,...,G. Dynasty Family Games,UCCPj_sLBX8XFA0Hua4kWVAg,7Qky82aFTg8,2024-07-21T02:00:05Z,None,NaN,NaN,None,NaN,NaN
2,youtube#playlistItem,whrN_aCXYq9zBu68te2eEmi0KH0,VVVDUGpfc0xCWDhYRkEwSHVhNGtXVkFnLllxZnBFUWc4V3Uw,2024-07-14T11:30:15Z,UCCPj_sLBX8XFA0Hua4kWVAg,Исследование в Spellforce 3: Reforced #12 «Око»,Spellforce 3: Reforced — продолжение интересно...,https://i.ytimg.com/vi/YqfpEQg8Wu0/default.jpg,120,90,...,G. Dynasty Family Games,UCCPj_sLBX8XFA0Hua4kWVAg,YqfpEQg8Wu0,2024-07-14T11:30:15Z,https://i.ytimg.com/vi/YqfpEQg8Wu0/sddefault.jpg,640.0,480.0,https://i.ytimg.com/vi/YqfpEQg8Wu0/maxresdefau...,1280.0,720.0
3,youtube#playlistItem,LYGT1-z6yyWN57f0oz7y88Vsd0Q,VVVDUGpfc0xCWDhYRkEwSHVhNGtXVkFnLlAwc09JYzBPS0Mw,2024-07-06T05:00:11Z,UCCPj_sLBX8XFA0Hua4kWVAg,Новая глава: Marvel's Guardians of the Galaxy ...,Marvel's Guardians of the Galaxy - это сюжетно...,https://i.ytimg.com/vi/P0sOIc0OKC0/default.jpg,120,90,...,G. Dynasty Family Games,UCCPj_sLBX8XFA0Hua4kWVAg,P0sOIc0OKC0,2024-07-06T05:00:11Z,https://i.ytimg.com/vi/P0sOIc0OKC0/sddefault.jpg,640.0,480.0,None,NaN,NaN
4,youtube#playlistItem,qHUFTV1xSNxffTR9NSSRI2IHWQg,VVVDUGpfc0xCWDhYRkEwSHVhNGtXVkFnLnA0WTkyNWhGYmM4,2024-06-30T03:00:27Z,UCCPj_sLBX8XFA0Hua4kWVAg,LOVECRAFT'S UNTOLD STORIES! ПРОХОЖДЕНИЕ НА РУС...,Это LOVECRAFT'S UNTOLD STORIES !!!ПРОХОЖДЕНИЕ ...,https://i.ytimg.com/vi/p4Y925hFbc8/default.jpg,120,90,...,G. Dynasty Family Games,UCCPj_sLBX8XFA0Hua4kWVAg,p4Y925hFbc8,2024-06-30T03:00:27Z,https://i.ytimg.com/vi/p4Y925hFbc8/sddefault.jpg,640.0,480.0,https://i.ytimg.com/vi/p4Y925hFbc8/maxresdefau...,1280.0,720.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6053537,youtube#playlistItem,pnbRYWW6yIspEXHqewl0aN1g2UU,VVVwN0plOEFST3pReGpYMVVNYXFZVXBRLlRseDhCZkJDUVYw,2011-08-04T18:25:34Z,UCp7Je8AROzQxjX1UMaqYUpQ,"Board Meeting: August 1, 2011",,https://i.ytimg.com/vi/Tlx8BfBCQV0/default.jpg,120,90,...,SBCCBoardofTrustees,UCp7Je8AROzQxjX1UMaqYUpQ,Tlx8BfBCQV0,2011-08-04T18:25:34Z,None,NaN,NaN,None,NaN,NaN
6053538,youtube#playlistItem,BpFmJGaU7_uuaPGW-AjjZzmLSUU,VVVwN0plOEFST3pReGpYMVVNYXFZVXBRLjVHT1lEMUVuc3RR,2011-08-02T19:02:35Z,UCp7Je8AROzQxjX1UMaqYUpQ,"Board Meeting: July 28, 2011",,https://i.ytimg.com/vi/5GOYD1EnstQ/default.jpg,120,90,...,SBCCBoardofTrustees,UCp7Je8AROzQxjX1UMaqYUpQ,5GOYD1EnstQ,2011-08-02T19:02:35Z,None,NaN,NaN,None,NaN,NaN
6053539,youtube#playlistItem,byWG5kE3ZAPfeg3dMXejROAyTno,VVVwN0plOEFST3pReGpYMVVNYXFZVXBRLndyTXBtSjRXQ2Jv,2011-06-14T22:40:22Z,UCp7Je8AROzQxjX1UMaqYUpQ,"Board Meeting: June 9, 2011",,https://i.ytimg.com/vi/wrMpmJ4WCbo/default.jpg,120,90,...,SBCCBoardofTrustees,UCp7Je8AROzQxjX1UMaqYUpQ,wrMpmJ4WCbo,2011-06-14T22:40:22Z,None,NaN,NaN,None,NaN,NaN
6053540,youtube#playlistItem,HoQjuxqyeiScmvgmfSaNjGB4954,VVVwN0plOEFST3pReGpYMVVNYXFZVXBRLjRHVFZpdUd0QXdJ,2011-06-09T17:26:33Z,UCp7Je8AROzQxjX1UMaqYUpQ,"Board Meeting: May 26, 2011",,https://i.ytimg.com/vi/4GTViuGtAwI/default.jpg,120,90,...,SBCCBoardofTrustees,UCp7Je8AROzQxjX1UMaqYUpQ,4GTViuGtAwI,2011-06-09T17:26:33Z,None,NaN,NaN,None,NaN,NaN
6053541,youtube#playlistItem,YCdiJoWYpWlkXvrui7zAmJij6pM,VVVwN0plOEFST3pReGpYMVVNYXFZVXBRLkNqcFd2dndpRGc0,2011-06-09T04:11:47Z,UCp7Je8AROzQxjX1UMaqYUpQ,"Board Meeting: April 28, 2011",,https://i.ytimg.com/vi/CjpWvvwiDg4/default.jpg,120,90,...,SBCCBoardofTrustees,UCp7Je8AROzQxjX1UMaqYUpQ,CjpWvvwiDg4,2011-06-09T04:11:47Z,None,NaN,NaN,None,NaN,NaN

In [17]:
videos = %sql SELECT * FROM videos;
videos_df = videos.DataFrame()
videos_df

,kind,etag,id,snippet.publishedAt,snippet.channelId,snippet.title,snippet.description,snippet.thumbnails.default.url,snippet.thumbnails.default.width,snippet.thumbnails.default.height,...,snippet.defaultLanguage,liveStreamingDetails.actualStartTime,liveStreamingDetails.actualEndTime,liveStreamingDetails.activeLiveChatId,liveStreamingDetails.scheduledStartTime,contentDetails.contentRating.ytRating,contentDetails.regionRestriction.blocked,liveStreamingDetails.concurrentViewers,liveStreamingDetails.scheduledEndTime,contentDetails.regionRestriction.allowed
0,youtube#video,8Tcj_ZIrkN-i_byhjrEUG5jT5Eg,s6cooBWPaLU,2024-07-28T02:45:02Z,UCCPj_sLBX8XFA0Hua4kWVAg,Раскрытие секретов CONTROL - Финал,Раскрытие темных секретов CONTROL. Это прохожд...,https://i.ytimg.com/vi/s6cooBWPaLU/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
1,youtube#video,hOTTFOceOH36HzTKSzHOotHaTac,7Qky82aFTg8,2024-07-21T02:00:05Z,UCCPj_sLBX8XFA0Hua4kWVAg,Увлекательная Deep Sky Derelicts ! Карты и ант...,Deep Sky Derelicts - это оригинальное сочетани...,https://i.ytimg.com/vi/7Qky82aFTg8/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
2,youtube#video,dBt8T8oc5u3k9M02bP24AXHDB28,YqfpEQg8Wu0,2024-07-14T11:30:15Z,UCCPj_sLBX8XFA0Hua4kWVAg,Исследование в Spellforce 3: Reforced #12 «Око»,Spellforce 3: Reforced — продолжение интересно...,https://i.ytimg.com/vi/YqfpEQg8Wu0/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
3,youtube#video,Q02tvMV6lSdzjkBjxu2eI6OziUM,P0sOIc0OKC0,2024-07-06T05:00:11Z,UCCPj_sLBX8XFA0Hua4kWVAg,Новая глава: Marvel's Guardians of the Galaxy ...,Marvel's Guardians of the Galaxy - это сюжетно...,https://i.ytimg.com/vi/P0sOIc0OKC0/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
4,youtube#video,78x1xEFtszNYuIqBaxiayBFuq5U,p4Y925hFbc8,2024-06-30T03:00:27Z,UCCPj_sLBX8XFA0Hua4kWVAg,LOVECRAFT'S UNTOLD STORIES! ПРОХОЖДЕНИЕ НА РУС...,Это LOVECRAFT'S UNTOLD STORIES !!!ПРОХОЖДЕНИЕ ...,https://i.ytimg.com/vi/p4Y925hFbc8/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1330370,youtube#video,npIfPpirM9RcxZughwWKYinDz_c,533Zp0QvKyo,2024-04-01T17:21:10Z,UCIVk1L1-JmpdiGuZcVjImtA,Tucson police update on officer killed in crash,Tucson police are holding a press conference a...,https://i.ytimg.com/vi/533Zp0QvKyo/default.jpg,120,90,...,None,2024-04-01T17:05:12Z,2024-04-01T17:19:22Z,None,None,None,None,None,None,None
1330371,youtube#video,z8DSQ8nca3DMCD0_hBoP5Gt2-dc,116mDqZ-W6Q,2024-04-01T16:40:19Z,UCIVk1L1-JmpdiGuZcVjImtA,Dignity Memorial shows how pre-planning funera...,((SL Advertiser)) Dignity Memorial talks about...,https://i.ytimg.com/vi/116mDqZ-W6Q/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
1330372,youtube#video,Om03PU5wFEVFwm2zpN9bfpXyzGw,CkqXO8fkOl8,2024-04-01T15:36:06Z,UCIVk1L1-JmpdiGuZcVjImtA,Man killed in stabbing near 19th and Glendale ...,Phoenix police are investigating a stabbing at...,https://i.ytimg.com/vi/CkqXO8fkOl8/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
1330373,youtube#video,wuxQ7_cG9XImY9VQL7W-YKOHep0,5X9lEHz3xaE,2024-04-01T14:38:22Z,UCIVk1L1-JmpdiGuZcVjImtA,'Caitlin Clark has changed my life': Scottsdal...,The Valley’s Caitlin Clark is a planning speci...,https://i.ytimg.com/vi/5X9lEHz3xaE/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None
1330374,youtube#video,Xk7caZWKRye1pWWfzW9PyuwBQME,PQRkWPrIWzc,2024-04-01T14:32:08Z,UCIVk1L1-JmpdiGuZcVjImtA,Tucson officer killed in crash near University...,The officer was reportedly responding to a cal...,https://i.ytimg.com/vi/PQRkWPrIWzc/default.jpg,120,90,...,None,None,None,None,None,None,None,None,None,None

In [18]:
search_results = %sql SELECT * FROM search_results;
search_results_df = search_results.DataFrame()
search_results

In [ ]:
### DATA PREPROCESSING ###

def rename_features(df):
    'Rename the features.'
    transform_df = df.copy()
    name_map = {
        'snippet.channelId': 'channel.id',
        'snippet.channelTitle': 'channel.name',
        'snippet.categoryId': 'video.category_id',
        'snippet.title': 'video.title',
        'snippet.description': 'video.description',
        'snippet.tags': 'video.tags',
        'snippet.publishedAt': 'video.published_at',
        'snippet.defaultAudioLanguage': 'language.default_audio',
        'snippet.defaultLanguage': 'language.default',
        'contentDetails.caption': 'details.has_captions',
        'contentDetails.duration': 'video.duration_seconds',
        'contentDetails.licensedContent': 'details.licensed_content',
        'contentDetails.contentRating.ytRating': 'details.is_age_restricted',
        'contentDetails.projection': 'details.is_rectangular',
        'contentDetails.definition': 'details.is_not_sd',
        'contentDetails.dimension': 'details.is_2d',
        'statistics.commentCount': 'stats.comment_count',
        'statistics.dislikeCount': 'stats.dislike_count',
        'statistics.favoriteCount': 'stats.favorite_count',
        'statistics.likeCount': 'stats.like_count',
        'statistics.viewCount': 'target.view_count',
        'topicDetails.topicCategories': 'video.topic_categories',
        'liveStreamingDetails.scheduledStartTime': 'live.scheduled_start_time',
        'liveStreamingDetails.scheduledEndTime': 'live.scheduled_end_time',
        'liveStreamingDetails.actualStartTime': 'live.actual_start_time',
        'liveStreamingDetails.actualEndTime': 'live.actual_end_time',
    }
    
    transform_df.rename(columns=name_map, inplace=True)
    return transform_df

def drop_inappropriate_data(df):
    'Drop data inappropriate for this use case.'
    transform_df = df.copy()
    # drop non ascii
    transform_df = transform_df[transform_df['video.title'].apply(lambda x: x.isascii())]
    # drop kinds other than video
    transform_df = transform_df[transform_df['kind'] == 'youtube#video']
    # drop live and upcoming broadcasts
    transform_df = transform_df[transform_df['snippet.liveBroadcastContent'] == 'none']
    return transform_df

def bool_conversion(df):
    'Convert the columns to boolean.'
    transform_df = df.copy()
    # convert caption
    transform_df['details.has_captions'] = transform_df['details.has_captions'].apply(lambda x: True if x == 'true' else False)
    # convert ytRating
    transform_df['details.is_age_restricted'] = transform_df['details.is_age_restricted'].apply(lambda x: False if x is None else True)
    # convert projection
    transform_df['details.is_rectangular'] = transform_df['details.is_rectangular'].apply(lambda x: True if x == 'rectangular' else False)
    # convert dimension
    transform_df['details.is_2d'] = transform_df['details.is_2d'].apply(lambda x: True if x == '2d' else False)
    # convert definition
    transform_df['details.is_not_sd'] = transform_df['details.is_not_sd'].apply(lambda x: True if x != 'sd' else False)
    # convert licensed content
    transform_df['details.licensed_content'] = transform_df['details.licensed_content'].astype(bool)
    return transform_df

def manage_time(df):
    'Manage the time columns.'
    transform_df = df.copy()
    # Convert the 'publishedAt' column to datetime
    transform_df['video.published_at'] = pd.to_datetime(transform_df['video.published_at'])
    # Convert the 'duration' column to seconds
    transform_df['video.duration_seconds'] = transform_df['video.duration_seconds'].apply(lambda x: pd.to_timedelta(x).seconds)
    # Get times to make calculations
    scheduled_start_time = pd.to_datetime(transform_df['live.scheduled_start_time'])
    scheduled_end_time = pd.to_datetime(transform_df['live.scheduled_end_time'])
    actual_start_time = pd.to_datetime(transform_df['live.actual_start_time'])
    actual_end_time = pd.to_datetime(transform_df['live.actual_end_time'])
    # if row has scheduled start time and end time, calculate the scheduled duration
    transform_df['live.scheduled_duration_seconds'] = (scheduled_end_time - scheduled_start_time).dt.total_seconds()
    # if row has scheduled start time and actual start time, calculate the tardiness
    transform_df['live.tardiness_seconds'] = (actual_start_time - scheduled_start_time).dt.total_seconds()
    # if row has actual end time and scheduled end time, calculate the overrun
    transform_df['live.overrun_seconds'] = (actual_end_time - scheduled_end_time).dt.total_seconds()
    # if row has actual start time, 'live' is True, else False
    transform_df['live'] = transform_df['live.scheduled_start_time'].apply(lambda x: True if pd.notnull(x) else False)
    # if row has scheduled start time and actual start time'live_scheduled' is True, else if has actual start time 'live scheduled is False, else None
    transform_df['live.scheduled'] = transform_df['live'] & transform_df['live.actual_start_time'].apply(lambda x: True if pd.notnull(x) else False)
    return transform_df

def drop_unnecessary_cols(df):
    'Drop unnecessary columns.'
    transform_df = df.copy()
    thumbnail_cols = [col for col in transform_df.columns if 'thumbnail' in col]
    region_cols = [col for col in transform_df.columns if 'region' in col]
    localized_cols = [col for col in transform_df.columns if 'local' in col]
    other_cols = ['kind', 'etag', 'snippet.liveBroadcastContent', 'liveStreamingDetails.activeLiveChatId', 'liveStreamingDetails.concurrentViewers']
    drop_cols = thumbnail_cols + region_cols + localized_cols + other_cols
    transform_df.drop(columns=drop_cols, inplace=True)
    # sort the columns alphabetically
    return transform_df

from sklearn.preprocessing import StandardScaler, MinMaxScaler

def target_scaling(df):
    'Scale the target variable.'
    transform_df = df.copy()
    # Group by 'snippet.channelId' and apply scaling
    for _, group in transform_df.groupby('channel.id'):
        transform_df.loc[group.index, 'target.min_max_scaled_view_count'] = MinMaxScaler().fit_transform(group[['target.view_count']])
        transform_df.loc[group.index, 'target.standard_scaled_view_count'] = StandardScaler().fit_transform(group[['target.view_count']])
    transform_df = transform_df.reindex(sorted(transform_df.columns), axis=1)
    return transform_df

def apply_conditions(df):
    'Apply conditions to the dataframe.'
    transform_df = df.copy()
    # drop rows where details.has_captions is False
    transform_df = transform_df[transform_df['details.has_captions']]
    # drop rows where details.is_2d is False
    transform_df = transform_df[transform_df['details.is_2d']]
    # drop rows where details.is_not_sd is False
    transform_df = transform_df[transform_df['details.is_not_sd']]
    # drop rows where details.is_rectangular is False
    transform_df = transform_df[transform_df['details.is_rectangular']]
    # drop rows where none of None, 'en', 'EN' in language.default_audio
    transform_df = transform_df[transform_df['language.default_audio'].apply(lambda x: x in [None, 'en', 'EN'])]
    # drop rows where none of None, 'en', 'EN' in language.default
    transform_df = transform_df[transform_df['language.default'].apply(lambda x: x in [None, 'en', 'EN'])]
    # drop rows where live is True
    transform_df = transform_df[~transform_df['live']]
    return transform_df

In [ ]:
# Preprocess the data for general usage

# Create a copy of the original dataframe and perform basic data cleaning
video_df = origin_df.copy()[[
    'id', 'snippet.publishedAt', 'snippet.title', 'snippet.description',  'snippet.tags', 
    'snippet.categoryId', 'snippet.channelId', 'snippet.defaultLanguage', 'snippet.defaultAudioLanguage', 
    'contentDetails.duration', 'contentDetails.caption', 'topicDetails.topicCategories',
    'statistics.viewCount']].set_index('id')

video_df = video_df[video_df['snippet.defaultLanguage'].str.contains('en', na=False)].drop(columns='snippet.defaultLanguage')
video_df = video_df[video_df['snippet.defaultAudioLanguage'].str.contains('en', na=False)].drop(columns='snippet.defaultAudioLanguage')

# drop ascii
video_df = video_df[video_df['snippet.title'].apply(lambda x: x.isascii())]

# drop non video kind



video_df

In [ ]:
### FEATURE ENGINEERING ###

def generate_capitalization_features(data):
    capital_df = data.copy()
    capital_df['num_capital_letters'] = capital_df['video.title'].apply(lambda x: sum(1 for c in x if c.isupper()))
    capital_df['num_all_caps_words'] = capital_df['video.title'].apply(lambda x: sum(1 for c in x.split() if c.isupper()))
    capital_df['num_capitalized_words'] = capital_df['video.title'].apply(lambda x: sum(1 for c in x.split() if c.istitle()))
    capital_df['pct_capital_letters'] = capital_df['num_capital_letters'] / capital_df['video.title'].apply(len)
    capital_df['pct_all_caps_words'] = capital_df['num_all_caps_words'] / capital_df['video.title'].apply(lambda x: len(x.split()))
    capital_df['pct_capitalized_words'] = capital_df['num_capitalized_words'] / capital_df['video.title'].apply(lambda x: len(x.split()))
    capital_df = capital_df.drop(columns=['video.title'])
    return capital_df

def generate_readability_features(data):
    reading_df = data.copy()
    try:
        reading_df['flesch_reading_ease'] = reading_df['video.title'].apply(lambda x: 206.835 - 1.015 * len(x.split()) - 84.6 * sum(1 for c in x if c.lower() in 'aeiouy') / len(x.split()))
        reading_df['flesch_kincaid_grade'] = reading_df['video.title'].apply(lambda x: 0.39 * len(x.split()) + 11.8 * sum(1 for c in x if c.lower() in 'aeiouy') / len(x.split()) - 15.59)
        reading_df['gunning_fog_index'] = reading_df['video.title'].apply(lambda x: 0.4 * (len(x.split()) + 100 * sum(1 for c in x if c in ['.', '!', '?'])) / len(x.split()))
        reading_df['smog_index'] = reading_df['video.title'].apply(lambda x: 1.043 * (30 * sum(1 for c in x if c in ['.', '!', '?']) / len(x.split())) ** 0.5 + 3.1291)
        reading_df['coleman_liau_index'] = reading_df['video.title'].apply(lambda x: 5.88 * sum(1 for c in x if c.isalnum()) / len(x) - 0.296 * 100 / len(x.split()) - 15.8)
        reading_df['automated_readability_index'] = reading_df['video.title'].apply(lambda x: 4.71 * len(x) / len(x.split()) + 0.5 * len(x.split()) - 21.43)
        reading_df['linsear_write_formula'] = reading_df['video.title'].apply(lambda x: (sum(1 for c in x if c.lower() in 'aeiouy') + sum(1 for c in x if c in ['.', '!', '?'])) / len(x.split()) / 2)
        reading_df['dale_chall_readability_score'] = reading_df['video.title'].apply(lambda x: 0.1579 * (100 * sum(1 for c in x if c.isalnum()) / len(x)) + 0.0496 * len(x.split()))
    except ZeroDivisionError:
        reading_df['flesch_reading_ease'] = 0
        reading_df['flesch_kincaid_grade'] = 0    
        reading_df['gunning_fog_index'] = 0
        reading_df['smog_index'] = 0
        reading_df['coleman_liau_index'] = 0
        reading_df['automated_readability_index'] = 0
        reading_df['linsear_write_formula'] = 0
        reading_df['dale_chall_readability_score'] = 0
    reading_df = reading_df.drop(columns=['video.title']).dropna()
    return reading_df

from nltk.tag import pos_tag

from nltk.tokenize import word_tokenize
from collections import Counter

def generate_pos_tags_df(data):
    pos_tags = data['video.title'].apply(lambda x: Counter(tag for word, tag in pos_tag(word_tokenize(x))))

    specific_pos_tags_count_df = pd.DataFrame(list(pos_tags), index=data.index)
    specific_pos_tags_count_df = specific_pos_tags_count_df.fillna(0)

    for col in specific_pos_tags_count_df.columns:
        if not col.isalnum():
            specific_pos_tags_count_df.drop(columns=col, inplace=True)

    generic_pos_tags_count_df = specific_pos_tags_count_df.copy()
    generic_pos_tags_count_df['noun'] = generic_pos_tags_count_df[['NN', 'NNS', 'NNP', 'NNPS']].sum(axis=1)
    generic_pos_tags_count_df['verb'] = generic_pos_tags_count_df[['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']].sum(axis=1)
    generic_pos_tags_count_df['adjective'] = generic_pos_tags_count_df[['JJ', 'JJR', 'JJS']].sum(axis=1)
    generic_pos_tags_count_df['adverb'] = generic_pos_tags_count_df[['RB', 'RBR', 'RBS']].sum(axis=1)
    generic_pos_tags_count_df['pronoun'] = generic_pos_tags_count_df[['PRP', 'WP']].sum(axis=1)
    generic_pos_tags_count_df['preposition'] = generic_pos_tags_count_df[['IN', 'TO']].sum(axis=1)
    generic_pos_tags_count_df['conjunction'] = generic_pos_tags_count_df[['CC']].sum(axis=1)
    generic_pos_tags_count_df['interjection'] = generic_pos_tags_count_df[['UH']].sum(axis=1)
    generic_pos_tags_count_df['determiner'] = generic_pos_tags_count_df[['DT', 'PDT', 'WDT']].sum(axis=1)
    generic_pos_tags_count_df = generic_pos_tags_count_df[['noun', 'verb', 'adjective', 'adverb', 'pronoun', 'preposition', 'conjunction', 'interjection', 'determiner']]

    specific_pos_tags_pct_df = specific_pos_tags_count_df.div(specific_pos_tags_count_df.sum(axis=1), axis=0)
    generic_pos_tags_pct_df = generic_pos_tags_count_df.div(generic_pos_tags_count_df.sum(axis=1), axis=0)

    specific_pos_tags_count_df.columns = ['specific_count.' + col for col in specific_pos_tags_count_df.columns]
    specific_pos_tags_pct_df.columns = ['specific_pct.' + col for col in specific_pos_tags_pct_df.columns]
    generic_pos_tags_count_df.columns = ['generic_count.' + col for col in generic_pos_tags_count_df.columns]
    generic_pos_tags_pct_df.columns = ['generic_pct.' + col for col in generic_pos_tags_pct_df.columns]

    all_pos_tags_df = pd.concat([specific_pos_tags_count_df, specific_pos_tags_pct_df, generic_pos_tags_count_df, generic_pos_tags_pct_df], axis=1).fillna(0)
    # add target column
    all_pos_tags_df['target.min_max_scaled_view_count'] = data['target.min_max_scaled_view_count']
    return all_pos_tags_df

import nltk
nltk.download('vader_lexicon')

# score sentiment
from nltk.sentiment.vader import SentimentIntensityAnalyzer
def generate_sentiment_df(data):
    sia = SentimentIntensityAnalyzer()

    sentiment_df = data.copy()
    sentiment_df['sentiment'] = sentiment_df['video.title'].apply(lambda x: sia.polarity_scores(x)['compound'])

    # get sentiment of each word
    def get_word_sentiment(title):
        return [sia.polarity_scores(word)['compound'] for word in title.split()]

    word_sentiment = data['video.title'].apply(get_word_sentiment)
    try:
        sentiment_df['avg_word_sentiment'] = word_sentiment.apply(lambda x: sum(x) / len(x))
    except ZeroDivisionError:
        sentiment_df['avg_word_sentiment'] = 0
    try:
        sentiment_df['max_word_sentiment'] = word_sentiment.apply(max)
        sentiment_df['min_word_sentiment'] = word_sentiment.apply(min)
    except ValueError:
        sentiment_df['max_word_sentiment'] = 0
        sentiment_df['min_word_sentiment'] = 0

    sentiment_df = sentiment_df.drop(columns=['video.title'])
    # pad with zeros
    max_len = max(len(sent) for sent in word_sentiment)
    word_sentiment = word_sentiment.apply(lambda x: x + [0] * (max_len - len(x)))
    word_sentiment_df = pd.DataFrame(word_sentiment.tolist(), index=word_sentiment.index)
    word_sentiment_df.columns = ['word.' + str(i) for i in word_sentiment_df.columns]
    sentiment_df = pd.concat([sentiment_df, word_sentiment_df], axis=1)
    return sentiment_df

def get_feature_significance(train_data_X, train_data_y):
    lasso_estimator = fit_get_lasso_estimator(train_data_X, train_data_y)
    lasso_coefficients = pd.Series(lasso_estimator.coef_, index=train_data_X.columns, name='coefficient')

    rf_estimator = fit_get_rf_estimator(train_data_X, train_data_y)
    rf_importances = pd.Series(rf_estimator.feature_importances_, index=train_data_X.columns, name='importance')

    features = pd.concat([lasso_coefficients, rf_importances], axis=1)
    features['score'] = features['coefficient'] * features['importance']
    features = features.sort_values('score', ascending=False)
    return features

In [ ]:
# Generate features

capital_train_df = generate_capitalization_features(train_df)
readability_train_df = generate_readability_features(train_df)
pos_tags_train_df = generate_pos_tags_df(train_df)
sentiment_train_df = generate_sentiment_df(train_df)

generated_train_dfs = [capital_train_df, readability_train_df, pos_tags_train_df, sentiment_train_df]
train_data_df = generated_train_dfs[0]
for df in generated_train_dfs[1:]:
    train_data_df = train_data_df.merge(df.drop(columns='target.min_max_scaled_view_count'), left_index=True, right_index=True)

capital_test_df = generate_capitalization_features(test_df)
readability_test_df = generate_readability_features(test_df)
pos_tags_test_df = generate_pos_tags_df(test_df)
sentiment_test_df = generate_sentiment_df(test_df)

generated_test_dfs = [capital_test_df, readability_test_df, pos_tags_test_df, sentiment_test_df]
test_data_df = generated_test_dfs[0]
for df in generated_test_dfs[1:]:
    test_data_df = test_data_df.merge(df.drop(columns='target.min_max_scaled_view_count'), left_index=True, right_index=True)

# for col in train_data_df.columns, if col not in test_data_df.columns, add to test_data_df with value 0
for col in train_data_df.columns:
    if col not in test_data_df.columns:
        test_data_df[col] = 0
# for col in test_data_df.columns, if col not in train_data_df.columns, drop from test_data_df
for col in test_data_df.columns:
    if col not in train_data_df.columns:
        test_data_df.drop(columns=col, inplace=True)
test_data_df = test_data_df[train_data_df.columns]

In [ ]:
### MODELING ###

from sklearn.preprocessing import MinMaxScaler

def scale_data(train_data, test_data, scaler=None):
    if not scaler:
        scaler = MinMaxScaler()
    train_data = pd.DataFrame(scaler.fit_transform(train_data),
                              columns=train_data.columns, 
                              index=train_data.index)
    test_data = pd.DataFrame(scaler.transform(test_data),
                             columns=test_data.columns, 
                             index=test_data.index)
    return train_data, test_data

# add to path
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..', 'src')))
from Selector import CombineCorrelatedFeaturesSelector

def combine_correlated_features(train_data, test_data, threshold=1):
    ccfs = CombineCorrelatedFeaturesSelector(threshold=threshold)
    train_data = ccfs.fit_transform(train_data)
    test_data = ccfs.transform(test_data)
    return train_data, test_data
    
from Selector import MutualInforegressionSelector

def select_by_mutual_inforegression(train_data, train_target, test_data, threshold=0):
    mirs = MutualInforegressionSelector(threshold=threshold)
    train_data = mirs.fit_transform(train_data, train_target)
    test_data = mirs.transform(test_data)
    return train_data, test_data

from Selector import VIFSelector

def select_by_variance_inflation_factor(train_data, test_data, threshold=10):
    vifs = VIFSelector(threshold=threshold)
    train_data = vifs.fit_transform(train_data)
    test_data = vifs.transform(test_data)
    return train_data, test_data

from Selector import CooksDistanceInfluenceSelector

def remove_influential_points(train_data, train_target):
    cd = CooksDistanceInfluenceSelector()
    train_data = cd.fit_transform(train_data, train_target)
    train_target = train_target.loc[train_data.index]
    return train_data, train_target

from sklearn.linear_model import Lasso
from sklearn.model_selection import RandomizedSearchCV

def fit_get_lasso_estimator(train_data, train_target):
    print('Lasso')
    lasso_params = { 'alpha' : [.1**i for i in range(10)] } 
    lasso = Lasso(max_iter=10000)
    lasso_search = RandomizedSearchCV(lasso, param_distributions=lasso_params, n_iter=8, cv=3, n_jobs=-1, verbose=2, random_state=42)
    lasso_search.fit(train_data, train_target)
    lasso_best_estimator = lasso_search.best_estimator_
    print(lasso_search.best_params_)
    print(lasso_search.best_score_)
    return lasso_best_estimator

from sklearn.ensemble import RandomForestRegressor

def fit_get_rf_estimator(train_data, train_target):
    print('Random Forest')
    rf_params = {
        'n_estimators': [2**i for i in range(13)],
        'max_features': ['sqrt', 'log2'],
        'max_depth': [2**i for i in range(11)],
        'min_samples_split': [2**i for i in range(1,9)],
        'min_samples_leaf': [2**i for i in range(1,9)]
    }                      
    rf = RandomForestRegressor()
    rf_search = RandomizedSearchCV(rf, param_distributions=rf_params, n_iter=16, cv=4, n_jobs=-1, verbose=2, random_state=42)
    rf_search.fit(train_data, train_target)
    rf_best_estimator = rf_search.best_estimator_
    print(rf_search.best_params_)
    print(rf_search.best_score_)
    return rf_best_estimator

def get_train_test_X_y(train_data, test_data, target_column_name):
    X_train = train_data.drop(columns=[target_column_name])
    y_train = train_data[target_column_name]
    X_test = test_data.drop(columns=[target_column_name])
    y_test = test_data[target_column_name]
    return X_train, y_train, X_test, y_test

In [ ]:
# # Build the models and extract features

# train_data_X, train_data_y, test_data_X, test_data_y = get_train_test_X_y(train_data_df, test_data_df, 'target.min_max_scaled_view_count')

# train_data_X, test_data_X = scale_data(train_data_X, test_data_X, MinMaxScaler())
# train_data_X, test_data_X = combine_correlated_features(train_data_X, test_data_X, threshold=.95)
# train_data_X, test_data_X = select_by_mutual_inforegression(train_data_X, train_data_y, test_data_X, threshold=0)
# train_data_X, test_data_X = select_by_variance_inflation_factor(train_data_X, test_data_X, threshold=10)
# train_data_X, train_data_y = remove_influential_points(train_data_X, train_data_y)

# features = get_feature_significance(train_data_X, train_data_y)
# features

In [ ]:
# import tfidf
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', min_df=0.0001, max_df=0.9)
train_tfidf_df = pd.DataFrame(tfidf.fit_transform(train_df['video.title']).toarray(), index=train_df.index, columns=tfidf.get_feature_names_out())
test_tfidf_df = pd.DataFrame(tfidf.transform(test_df['video.title']).toarray(), index=test_df.index, columns=tfidf.get_feature_names_out())

In [ ]:
train_tfidf_df, test_tfidf_df = scale_data(train_tfidf_df, test_tfidf_df)

In [ ]:
train_tfidf_df, test_tfidf_df = combine_correlated_features(train_tfidf_df, test_tfidf_df, threshold=1)

In [ ]:
train_tfidf_df, test_tfidf_df = select_by_mutual_inforegression(train_tfidf_df, train_data_y, test_tfidf_df, threshold=0)

In [ ]:
train_tfidf_df, test_tfidf_df = select_by_variance_inflation_factor(train_tfidf_df, test_tfidf_df, threshold=10)

In [ ]:
train_tfidf_df, train_data_y = remove_influential_points(train_tfidf_df, train_data_y)

In [ ]:
train_tfidf_df